"use strict";
// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file archera/v1/archera.proto (package blueapi.archera.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Archera = exports.ListOrgsRequestSchema = exports.OrgSchema = exports.file_archera_v1_archera = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
const annotations_pb_1 = require("../../google/api/annotations_pb");
const annotations_pb_2 = require("../../protoc-gen-openapiv2/options/annotations_pb");
/**
 * Describes the file archera/v1/archera.proto.
 */
exports.file_archera_v1_archera = (0, codegenv2_1.fileDesc)("ChhhcmNoZXJhL3YxL2FyY2hlcmEucHJvdG8SEmJsdWVhcGkuYXJjaGVyYS52MSIxCgNPcmcSDQoFb3JnSWQYASABKAkSDAoEbmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCSIRCg9MaXN0T3Jnc1JlcXVlc3QymQIKB0FyY2hlcmESbQoITGlzdE9yZ3MSIy5ibHVlYXBpLmFyY2hlcmEudjEuTGlzdE9yZ3NSZXF1ZXN0GhcuYmx1ZWFwaS5hcmNoZXJhLnYxLk9yZyIhgtPkkwIbOgEqIhYvdjEvb3JnYW5pemF0aW9uczpyZWFkMAEangGSQZoBEkcoQWxwaGEpIEFyY2hlcmEgQVBJLiBCYXNlIFVSTDogaHR0cHM6Ly9hcGkuYWxwaGF1cy5jbG91ZC9tL2JsdWUvYXJjaGVyYRpPChJTZXJ2aWNlIGRlZmluaXRpb24SOWh0dHBzOi8vZ2l0aHViLmNvbS9hbHBoYXVzbGFicy9ibHVlYXBpL3RyZWUvbWFpbi9hcmNoZXJhL0JRChljbG91ZC5hbHBoYXVzLmFwaS5hcmNoZXJhQgxBcmNoZXJhUHJvdG9aJmdpdGh1Yi5jb20vYWxwaGF1c2xhYnMvYmx1ZWFwaS9hcmNoZXJhYgZwcm90bzM", [annotations_pb_1.file_google_api_annotations, annotations_pb_2.file_protoc_gen_openapiv2_options_annotations]);
/**
 * Describes the message blueapi.archera.v1.Org.
 * Use `create(OrgSchema)` to create a new message.
 */
exports.OrgSchema = (0, codegenv2_1.messageDesc)(exports.file_archera_v1_archera, 0);
/**
 * Describes the message blueapi.archera.v1.ListOrgsRequest.
 * Use `create(ListOrgsRequestSchema)` to create a new message.
 */
exports.ListOrgsRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_archera_v1_archera, 1);
/**
 * Archera service definition.
 *
 * @generated from service blueapi.archera.v1.Archera
 */
exports.Archera = (0, codegenv2_1.serviceDesc)(exports.file_archera_v1_archera, 0);
