"use strict";
// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file api/cover/recommendation/azurecsp.proto (package blueapi.api.cover.recommendation.azurecsp, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AzureCSPRecommendationsSchema = exports.file_api_cover_recommendation_azurecsp = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
/**
 * Describes the file api/cover/recommendation/azurecsp.proto.
 */
exports.file_api_cover_recommendation_azurecsp = (0, codegenv2_1.fileDesc)("CidhcGkvY292ZXIvcmVjb21tZW5kYXRpb24vYXp1cmVjc3AucHJvdG8SKWJsdWVhcGkuYXBpLmNvdmVyLnJlY29tbWVuZGF0aW9uLmF6dXJlY3NwIhkKF0F6dXJlQ1NQUmVjb21tZW5kYXRpb25zQpIBCi5jbG91ZC5hbHBoYXVzLmJsdWVhcGkuYXBpLmNvdmVyLnJlY29tbWVuZGF0aW9uQiNBcGlDb3ZlckF6dXJlQ3NwUmVjb21tZW5kYXRpb25Qcm90b1o7Z2l0aHViLmNvbS9hbHBoYXVzbGFicy9ibHVlLXNkay1nby9hcGkvY292ZXIvcmVjb21tZW5kYXRpb25iBnByb3RvMw");
/**
 * Describes the message blueapi.api.cover.recommendation.azurecsp.AzureCSPRecommendations.
 * Use `create(AzureCSPRecommendationsSchema)` to create a new message.
 */
exports.AzureCSPRecommendationsSchema = (0, codegenv2_1.messageDesc)(exports.file_api_cover_recommendation_azurecsp, 0);
