// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file api/cover/recommendation/gcp.proto (package blueapi.api.cover.recommendation.gcp, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/cover/recommendation/gcp.proto.
 */
export const file_api_cover_recommendation_gcp: GenFile = /*@__PURE__*/
  fileDesc("CiJhcGkvY292ZXIvcmVjb21tZW5kYXRpb24vZ2NwLnByb3RvEiRibHVlYXBpLmFwaS5jb3Zlci5yZWNvbW1lbmRhdGlvbi5nY3AihgEKEkdDUFJlY29tbWVuZGF0aW9ucxJwCiByZWNvbW1lbmRhdGlvbkh1YlJlY29tbWVuZGF0aW9ucxgBIAEoCzJGLmJsdWVhcGkuYXBpLmNvdmVyLnJlY29tbWVuZGF0aW9uLmdjcC5SZWNvbW1lbmRhdGlvbkh1YlJlY29tbWVuZGF0aW9ucyKpAgogUmVjb21tZW5kYXRpb25IdWJSZWNvbW1lbmRhdGlvbnMSYQoIaW5zaWdodHMYASADKAsyTy5ibHVlYXBpLmFwaS5jb3Zlci5yZWNvbW1lbmRhdGlvbi5nY3AuUmVjb21tZW5kYXRpb25IdWJSZWNvbW1lbmRhdGlvbnMuSW5zaWdodHMSGQoRcmVjb21tZW5kZWRBY3Rpb24YAiABKAkSEAoIcmVzb3VyY2UYAyABKAkSFQoNcHJpb3JpdHlMZXZlbBgEIAEoCRIvCg5hZGRpdGlvbmFsRGF0YRgFIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QaLQoISW5zaWdodHMSDAoEdHlwZRgBIAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCUKNAQouY2xvdWQuYWxwaGF1cy5ibHVlYXBpLmFwaS5jb3Zlci5yZWNvbW1lbmRhdGlvbkIeQXBpQ292ZXJHY3BSZWNvbW1lbmRhdGlvblByb3RvWjtnaXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWUtc2RrLWdvL2FwaS9jb3Zlci9yZWNvbW1lbmRhdGlvbmIGcHJvdG8z", [file_google_protobuf_struct]);

/**
 * @generated from message blueapi.api.cover.recommendation.gcp.GCPRecommendations
 */
export type GCPRecommendations = Message<"blueapi.api.cover.recommendation.gcp.GCPRecommendations"> & {
  /**
   * @generated from field: blueapi.api.cover.recommendation.gcp.RecommendationHubRecommendations recommendationHubRecommendations = 1;
   */
  recommendationHubRecommendations?: RecommendationHubRecommendations;
};

/**
 * Describes the message blueapi.api.cover.recommendation.gcp.GCPRecommendations.
 * Use `create(GCPRecommendationsSchema)` to create a new message.
 */
export const GCPRecommendationsSchema: GenMessage<GCPRecommendations> = /*@__PURE__*/
  messageDesc(file_api_cover_recommendation_gcp, 0);

/**
 * @generated from message blueapi.api.cover.recommendation.gcp.RecommendationHubRecommendations
 */
export type RecommendationHubRecommendations = Message<"blueapi.api.cover.recommendation.gcp.RecommendationHubRecommendations"> & {
  /**
   * @generated from field: repeated blueapi.api.cover.recommendation.gcp.RecommendationHubRecommendations.Insights insights = 1;
   */
  insights: RecommendationHubRecommendations_Insights[];

  /**
   * @generated from field: string recommendedAction = 2;
   */
  recommendedAction: string;

  /**
   * @generated from field: string resource = 3;
   */
  resource: string;

  /**
   * @generated from field: string priorityLevel = 4;
   */
  priorityLevel: string;

  /**
   * @generated from field: google.protobuf.Struct additionalData = 5;
   */
  additionalData?: JsonObject;
};

/**
 * Describes the message blueapi.api.cover.recommendation.gcp.RecommendationHubRecommendations.
 * Use `create(RecommendationHubRecommendationsSchema)` to create a new message.
 */
export const RecommendationHubRecommendationsSchema: GenMessage<RecommendationHubRecommendations> = /*@__PURE__*/
  messageDesc(file_api_cover_recommendation_gcp, 1);

/**
 * @generated from message blueapi.api.cover.recommendation.gcp.RecommendationHubRecommendations.Insights
 */
export type RecommendationHubRecommendations_Insights = Message<"blueapi.api.cover.recommendation.gcp.RecommendationHubRecommendations.Insights"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message blueapi.api.cover.recommendation.gcp.RecommendationHubRecommendations.Insights.
 * Use `create(RecommendationHubRecommendations_InsightsSchema)` to create a new message.
 */
export const RecommendationHubRecommendations_InsightsSchema: GenMessage<RecommendationHubRecommendations_Insights> = /*@__PURE__*/
  messageDesc(file_api_cover_recommendation_gcp, 1, 0);

