// @generated by protoc-gen-es v2.7.0
// @generated from file api/ripple/billinggroup.proto (package blueapi.api.ripple, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file api/ripple/billinggroup.proto.
 */
export const file_api_ripple_billinggroup = /*@__PURE__*/
  fileDesc("Ch1hcGkvcmlwcGxlL2JpbGxpbmdncm91cC5wcm90bxISYmx1ZWFwaS5hcGkucmlwcGxlIvICChBCaWxsaW5nR3JvdXBJbmZvEhQKDGJpbGxpbmdUaXRsZRgBIAEoCRITCgtwaG9uZU51bWJlchgCIAEoCRISCgpwb3N0YWxDb2RlGAMgASgJEg8KB2FkZHJlc3MYBCABKAkSEAoIcGVyc29uYWwYBSABKAkSDwoHcmVtYXJrcxgGIAEoCRIRCglwcm9qZWN0SWQYByABKAkSEAoIbGFuZ3VhZ2UYCCABKAkSEwoLZGlzcGxheUNvc3QYCSABKAkSGAoQZXhjaGFuZ2VSYXRlVHlwZRgKIAEoCRIOCgZxckNvZGUYCyABKAgSGQoRaW52b2ljZVRlbXBsYXRlSWQYDCABKAkSDAoEY2l0eRgNIAEoCRISCgpwcmVmZWN0dXJlGA4gASgJEg8KB2NvdW50cnkYDyABKAkSDQoFc3RhdGUYECABKAkSFAoMYWRkcmVzc0xpbmUxGBEgASgJEhQKDGFkZHJlc3NMaW5lMhgSIAEoCUJxCiBjbG91ZC5hbHBoYXVzLmJsdWVhcGkuYXBpLnJpcHBsZUIeQXBpUmlwcGxlQmlsbGluZ0dyb3VwSW5mb1Byb3RvWi1naXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWUtc2RrLWdvL2FwaS9yaXBwbGViBnByb3RvMw");

/**
 * Describes the message blueapi.api.ripple.BillingGroupInfo.
 * Use `create(BillingGroupInfoSchema)` to create a new message.
 */
export const BillingGroupInfoSchema = /*@__PURE__*/
  messageDesc(file_api_ripple_billinggroup, 0);

