// @generated by protoc-gen-es v2.7.0
// @generated from file api/ripple/rounding.proto (package blueapi.api.ripple, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/ripple/rounding.proto.
 */
export declare const file_api_ripple_rounding: GenFile;

/**
 * Rounding resource definition.
 *
 * @generated from message blueapi.api.ripple.Rounding
 */
export declare type Rounding = Message<"blueapi.api.ripple.Rounding"> & {
  /**
   * The rounding method.
   *
   * @generated from field: blueapi.api.ripple.Rounding.RoundingMethod rounding = 1;
   */
  rounding: Rounding_RoundingMethod;
};

/**
 * Describes the message blueapi.api.ripple.Rounding.
 * Use `create(RoundingSchema)` to create a new message.
 */
export declare const RoundingSchema: GenMessage<Rounding>;

/**
 * RoundingMethod
 *
 * @generated from enum blueapi.api.ripple.Rounding.RoundingMethod
 */
export enum Rounding_RoundingMethod {
  /**
   * round
   *
   * @generated from enum value: ROUND = 0;
   */
  ROUND = 0,

  /**
   * round up
   *
   * @generated from enum value: ROUNDUP = 1;
   */
  ROUNDUP = 1,

  /**
   * round down
   *
   * @generated from enum value: ROUNDDOWN = 2;
   */
  ROUNDDOWN = 2,
}

/**
 * Describes the enum blueapi.api.ripple.Rounding.RoundingMethod.
 */
export declare const Rounding_RoundingMethodSchema: GenEnum<Rounding_RoundingMethod>;

