"use strict";
// @generated by protoc-gen-es v2.5.0 with parameter "target=ts"
// @generated from file api/ripple/untaggedgroup.proto (package blueapi.api.ripple, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AssignedSchema = exports.AssignedBillingGroupSchema = exports.UntaggedGroupSchema = exports.file_api_ripple_untaggedgroup = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
const account_pb_1 = require("../account_pb");
const field_behavior_pb_1 = require("../../google/api/field_behavior_pb");
/**
 * Describes the file api/ripple/untaggedgroup.proto.
 */
exports.file_api_ripple_untaggedgroup = (0, codegenv2_1.fileDesc)("Ch5hcGkvcmlwcGxlL3VudGFnZ2VkZ3JvdXAucHJvdG8SEmJsdWVhcGkuYXBpLnJpcHBsZSLaAQoNVW50YWdnZWRHcm91cBIKCgJpZBgBIAEoCRISCgRuYW1lGAIgASgJQgTiQQECEjQKCGFzc2lnbmVkGAMgASgLMhwuYmx1ZWFwaS5hcGkucmlwcGxlLkFzc2lnbmVkQgTiQQEBEkUKDWJpbGxpbmdHcm91cHMYBCADKAsyKC5ibHVlYXBpLmFwaS5yaXBwbGUuQXNzaWduZWRCaWxsaW5nR3JvdXBCBOJBAQESFQoHY3JlYXRlZBgFIAEoCUIE4kEBAxIVCgd1cGRhdGVkGAYgASgJQgTiQQEDIp4BChRBc3NpZ25lZEJpbGxpbmdHcm91cBIKCgJpZBgBIAEoCRIPCgdncm91cElkGAIgASgJEhEKCWdyb3VwTmFtZRgDIAEoCRImCghhY2NvdW50cxgEIAMoCzIULmJsdWVhcGkuYXBpLkFjY291bnQSLgoIYXNzaWduZWQYBSABKAsyHC5ibHVlYXBpLmFwaS5yaXBwbGUuQXNzaWduZWQiOQoIQXNzaWduZWQSGAoKcGVyY2VudGFnZRgBIAEoBUIE4kEBAhITCgVmaXhlZBgCIAEoBUIE4kEBAkJuCiBjbG91ZC5hbHBoYXVzLmJsdWVhcGkuYXBpLnJpcHBsZUIbQXBpUmlwcGxlVW50YWdnZWRHcm91cFByb3RvWi1naXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWUtc2RrLWdvL2FwaS9yaXBwbGViBnByb3RvMw", [account_pb_1.file_api_account, field_behavior_pb_1.file_google_api_field_behavior]);
/**
 * Describes the message blueapi.api.ripple.UntaggedGroup.
 * Use `create(UntaggedGroupSchema)` to create a new message.
 */
exports.UntaggedGroupSchema = (0, codegenv2_1.messageDesc)(exports.file_api_ripple_untaggedgroup, 0);
/**
 * Describes the message blueapi.api.ripple.AssignedBillingGroup.
 * Use `create(AssignedBillingGroupSchema)` to create a new message.
 */
exports.AssignedBillingGroupSchema = (0, codegenv2_1.messageDesc)(exports.file_api_ripple_untaggedgroup, 1);
/**
 * Describes the message blueapi.api.ripple.Assigned.
 * Use `create(AssignedSchema)` to create a new message.
 */
exports.AssignedSchema = (0, codegenv2_1.messageDesc)(exports.file_api_ripple_untaggedgroup, 2);
