// @generated by protoc-gen-es v2.7.0
// @generated from file api/ripple/untaggedgroup.proto (package blueapi.api.ripple, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_api_account } from "../account_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";

/**
 * Describes the file api/ripple/untaggedgroup.proto.
 */
export const file_api_ripple_untaggedgroup = /*@__PURE__*/
  fileDesc("Ch5hcGkvcmlwcGxlL3VudGFnZ2VkZ3JvdXAucHJvdG8SEmJsdWVhcGkuYXBpLnJpcHBsZSLaAQoNVW50YWdnZWRHcm91cBIKCgJpZBgBIAEoCRISCgRuYW1lGAIgASgJQgTiQQECEjQKCGFzc2lnbmVkGAMgASgLMhwuYmx1ZWFwaS5hcGkucmlwcGxlLkFzc2lnbmVkQgTiQQEBEkUKDWJpbGxpbmdHcm91cHMYBCADKAsyKC5ibHVlYXBpLmFwaS5yaXBwbGUuQXNzaWduZWRCaWxsaW5nR3JvdXBCBOJBAQESFQoHY3JlYXRlZBgFIAEoCUIE4kEBAxIVCgd1cGRhdGVkGAYgASgJQgTiQQEDIp4BChRBc3NpZ25lZEJpbGxpbmdHcm91cBIKCgJpZBgBIAEoCRIPCgdncm91cElkGAIgASgJEhEKCWdyb3VwTmFtZRgDIAEoCRImCghhY2NvdW50cxgEIAMoCzIULmJsdWVhcGkuYXBpLkFjY291bnQSLgoIYXNzaWduZWQYBSABKAsyHC5ibHVlYXBpLmFwaS5yaXBwbGUuQXNzaWduZWQiOQoIQXNzaWduZWQSGAoKcGVyY2VudGFnZRgBIAEoBUIE4kEBAhITCgVmaXhlZBgCIAEoBUIE4kEBAkJuCiBjbG91ZC5hbHBoYXVzLmJsdWVhcGkuYXBpLnJpcHBsZUIbQXBpUmlwcGxlVW50YWdnZWRHcm91cFByb3RvWi1naXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWUtc2RrLWdvL2FwaS9yaXBwbGViBnByb3RvMw", [file_api_account, file_google_api_field_behavior]);

/**
 * Describes the message blueapi.api.ripple.UntaggedGroup.
 * Use `create(UntaggedGroupSchema)` to create a new message.
 */
export const UntaggedGroupSchema = /*@__PURE__*/
  messageDesc(file_api_ripple_untaggedgroup, 0);

/**
 * Describes the message blueapi.api.ripple.AssignedBillingGroup.
 * Use `create(AssignedBillingGroupSchema)` to create a new message.
 */
export const AssignedBillingGroupSchema = /*@__PURE__*/
  messageDesc(file_api_ripple_untaggedgroup, 1);

/**
 * Describes the message blueapi.api.ripple.Assigned.
 * Use `create(AssignedSchema)` to create a new message.
 */
export const AssignedSchema = /*@__PURE__*/
  messageDesc(file_api_ripple_untaggedgroup, 2);

