// @generated by protoc-gen-es v2.7.0
// @generated from file api/ripple/yearmonth.proto (package blueapi.api.ripple, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/ripple/yearmonth.proto.
 */
export declare const file_api_ripple_yearmonth: GenFile;

/**
 * YearMonth resource definition.
 *
 * @generated from message blueapi.api.ripple.YearMonth
 */
export declare type YearMonth = Message<"blueapi.api.ripple.YearMonth"> & {
  /**
   * List of the yearmonth.
   *
   * @generated from field: string yearMonth = 1;
   */
  yearMonth: string;
};

/**
 * Describes the message blueapi.api.ripple.YearMonth.
 * Use `create(YearMonthSchema)` to create a new message.
 */
export declare const YearMonthSchema: GenMessage<YearMonth>;

