"use strict";
// @generated by protoc-gen-es v2.5.0 with parameter "target=ts"
// @generated from file api/pricing/details.proto (package blueapi.api.pricing, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PricingDataSchema = exports.file_api_pricing_details = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
const wkt_1 = require("@bufbuild/protobuf/wkt");
/**
 * Describes the file api/pricing/details.proto.
 */
exports.file_api_pricing_details = (0, codegenv2_1.fileDesc)("ChlhcGkvcHJpY2luZy9kZXRhaWxzLnByb3RvEhNibHVlYXBpLmFwaS5wcmljaW5nIqQBCgtQcmljaW5nRGF0YRIOCgZ2ZW5kb3IYASABKAkSDwoHc2VydmljZRgCIAEoCRISCgpyZWdpb25Db2RlGAMgASgJEgsKA3NrdRgEIAEoCRIMCgR1bml0GAUgASgJEhQKDHByaWNlUGVyVW5pdBgGIAEoARIvCg5zZXJ2aWNlRGV0YWlscxgHIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RCawohY2xvdWQuYWxwaGF1cy5ibHVlYXBpLmFwaS5wcmljaW5nQhZBcGlQcmljaW5nRGV0YWlsc1Byb3RvWi5naXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWUtc2RrLWdvL2FwaS9wcmljaW5nYgZwcm90bzM", [wkt_1.file_google_protobuf_struct]);
/**
 * Describes the message blueapi.api.pricing.PricingData.
 * Use `create(PricingDataSchema)` to create a new message.
 */
exports.PricingDataSchema = (0, codegenv2_1.messageDesc)(exports.file_api_pricing_details, 0);
