// Copyright 2018 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.7.0
// @generated from file google/api/backend.proto (package google.api, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file google/api/backend.proto.
 */
export const file_google_api_backend = /*@__PURE__*/
  fileDesc("Chhnb29nbGUvYXBpL2JhY2tlbmQucHJvdG8SCmdvb2dsZS5hcGkiMQoHQmFja2VuZBImCgVydWxlcxgBIAMoCzIXLmdvb2dsZS5hcGkuQmFja2VuZFJ1bGUiWAoLQmFja2VuZFJ1bGUSEAoIc2VsZWN0b3IYASABKAkSDwoHYWRkcmVzcxgCIAEoCRIQCghkZWFkbGluZRgDIAEoARIUCgxtaW5fZGVhZGxpbmUYBCABKAFCbgoOY29tLmdvb2dsZS5hcGlCDEJhY2tlbmRQcm90b1ABWkVnb29nbGUuZ29sYW5nLm9yZy9nZW5wcm90by9nb29nbGVhcGlzL2FwaS9zZXJ2aWNlY29uZmlnO3NlcnZpY2Vjb25maWeiAgRHQVBJYgZwcm90bzM");

/**
 * Describes the message google.api.Backend.
 * Use `create(BackendSchema)` to create a new message.
 */
export const BackendSchema = /*@__PURE__*/
  messageDesc(file_google_api_backend, 0);

/**
 * Describes the message google.api.BackendRule.
 * Use `create(BackendRuleSchema)` to create a new message.
 */
export const BackendRuleSchema = /*@__PURE__*/
  messageDesc(file_google_api_backend, 1);

