// Copyright 2018 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.7.0
// @generated from file google/api/label.proto (package google.api, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file google/api/label.proto.
 */
export declare const file_google_api_label: GenFile;

/**
 * A description of a label.
 *
 * @generated from message google.api.LabelDescriptor
 */
export declare type LabelDescriptor = Message<"google.api.LabelDescriptor"> & {
  /**
   * The label key.
   *
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * The type of data that can be assigned to the label.
   *
   * @generated from field: google.api.LabelDescriptor.ValueType value_type = 2;
   */
  valueType: LabelDescriptor_ValueType;

  /**
   * A human-readable description for the label.
   *
   * @generated from field: string description = 3;
   */
  description: string;
};

/**
 * Describes the message google.api.LabelDescriptor.
 * Use `create(LabelDescriptorSchema)` to create a new message.
 */
export declare const LabelDescriptorSchema: GenMessage<LabelDescriptor>;

/**
 * Value types that can be used as label values.
 *
 * @generated from enum google.api.LabelDescriptor.ValueType
 */
export enum LabelDescriptor_ValueType {
  /**
   * A variable-length string. This is the default.
   *
   * @generated from enum value: STRING = 0;
   */
  STRING = 0,

  /**
   * Boolean; true or false.
   *
   * @generated from enum value: BOOL = 1;
   */
  BOOL = 1,

  /**
   * A 64-bit signed integer.
   *
   * @generated from enum value: INT64 = 2;
   */
  INT64 = 2,
}

/**
 * Describes the enum google.api.LabelDescriptor.ValueType.
 */
export declare const LabelDescriptor_ValueTypeSchema: GenEnum<LabelDescriptor_ValueType>;

