// Copyright 2018 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.7.0
// @generated from file google/api/source_info.proto (package google.api, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file google/api/source_info.proto.
 */
export const file_google_api_source_info = /*@__PURE__*/
  fileDesc("Chxnb29nbGUvYXBpL3NvdXJjZV9pbmZvLnByb3RvEgpnb29nbGUuYXBpIjgKClNvdXJjZUluZm8SKgoMc291cmNlX2ZpbGVzGAEgAygLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUJxCg5jb20uZ29vZ2xlLmFwaUIPU291cmNlSW5mb1Byb3RvUAFaRWdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFwaXMvYXBpL3NlcnZpY2Vjb25maWc7c2VydmljZWNvbmZpZ6ICBEdBUEliBnByb3RvMw", [file_google_protobuf_any]);

/**
 * Describes the message google.api.SourceInfo.
 * Use `create(SourceInfoSchema)` to create a new message.
 */
export const SourceInfoSchema = /*@__PURE__*/
  messageDesc(file_google_api_source_info, 0);

