// @generated by protoc-gen-connect-query v2.1.1
// @generated from file prism/v1/prism.proto (package blueapi.prism.v1, syntax proto3)
/* eslint-disable */

import { Prism } from "./prism_pb";

/**
 * Test endpoint only.
 *
 * @generated from rpc blueapi.prism.v1.Prism.Test
 */
export const test: typeof Prism["method"]["test"];
/**
 * WIP: Creates a new project.
 *
 * @generated from rpc blueapi.prism.v1.Prism.CreateProject
 */
export const createProject: typeof Prism["method"]["createProject"];
/**
 * WIP: Gets information about a project by ID.
 *
 * @generated from rpc blueapi.prism.v1.Prism.GetProject
 */
export const getProject: typeof Prism["method"]["getProject"];
/**
 * WIP: Deletes a project by ID.
 *
 * @generated from rpc blueapi.prism.v1.Prism.DeleteProject
 */
export const deleteProject: typeof Prism["method"]["deleteProject"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.CreateOrganization
 */
export const createOrganization: typeof Prism["method"]["createOrganization"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.GetOrganization
 */
export const getOrganization: typeof Prism["method"]["getOrganization"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.UpdateOrganization
 */
export const updateOrganization: typeof Prism["method"]["updateOrganization"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.DeleteOrganization
 */
export const deleteOrganization: typeof Prism["method"]["deleteOrganization"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.VerifyUser
 */
export const verifyUser: typeof Prism["method"]["verifyUser"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.CreateTeam
 */
export const createTeam: typeof Prism["method"]["createTeam"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.GetTeam
 */
export const getTeam: typeof Prism["method"]["getTeam"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.CreateProduct
 */
export const createProduct: typeof Prism["method"]["createProduct"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.DeleteProduct
 */
export const deleteProduct: typeof Prism["method"]["deleteProduct"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.AssignProjectToTeam
 */
export const assignProjectToTeam: typeof Prism["method"]["assignProjectToTeam"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.DeleteTeam
 */
export const deleteTeam: typeof Prism["method"]["deleteTeam"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.GetIntegrationStatus
 */
export const getIntegrationStatus: typeof Prism["method"]["getIntegrationStatus"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.UpdateReportSchedule
 */
export const updateReportSchedule: typeof Prism["method"]["updateReportSchedule"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.CreateReportSchedule
 */
export const createReportSchedule: typeof Prism["method"]["createReportSchedule"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.UpdateOrgTimezone
 */
export const updateOrgTimezone: typeof Prism["method"]["updateOrgTimezone"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.UpdateWorkflow
 */
export const updateWorkflow: typeof Prism["method"]["updateWorkflow"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.JoinOrganization
 */
export const joinOrganization: typeof Prism["method"]["joinOrganization"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.GenerateOrganizationCode
 */
export const generateOrganizationCode: typeof Prism["method"]["generateOrganizationCode"];
/**
 * @generated from rpc blueapi.prism.v1.Prism.ShareGDrive
 */
export const shareGDrive: typeof Prism["method"]["shareGDrive"];
