"use strict";
// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file api/aws/calculator.proto (package blueapi.api.aws, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalculatorConfigSchema = exports.ExcludedServiceFromUsageSchema = exports.AdjustmentsTypeListSchema = exports.AccountMonthlyCostCalculatedSchema = exports.file_api_aws_calculator = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
/**
 * Describes the file api/aws/calculator.proto.
 */
exports.file_api_aws_calculator = (0, codegenv2_1.fileDesc)("ChhhcGkvYXdzL2NhbGN1bGF0b3IucHJvdG8SD2JsdWVhcGkuYXBpLmF3cyLUAQocQWNjb3VudE1vbnRobHlDb3N0Q2FsY3VsYXRlZBIPCgdhY2NvdW50GAEgASgJEg0KBW1vbnRoGAIgASgJEhEKCXRpbWVzdGFtcBgDIAEoCRINCgVydW5JZBgEIAEoCRJFCgRtZXRhGAUgAygLMjcuYmx1ZWFwaS5hcGkuYXdzLkFjY291bnRNb250aGx5Q29zdENhbGN1bGF0ZWQuTWV0YUVudHJ5GisKCU1ldGFFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIiQKE0FkanVzdG1lbnRzVHlwZUxpc3QSDQoFdHlwZXMYASADKAkiagoYRXhjbHVkZWRTZXJ2aWNlRnJvbVVzYWdlEhkKEW1hbmFnZW1lbnRBY2NvdW50GAEgASgJEhMKC3Byb2R1Y3RDb2RlGAIgASgJEh4KFmNvbnZlcnRlZFRvQWRqdXN0bWVudHMYAyABKAgiowEKEENhbGN1bGF0b3JDb25maWcSQQoTYWRqdXN0bWVudHNUeXBlTGlzdBgBIAEoCzIkLmJsdWVhcGkuYXBpLmF3cy5BZGp1c3RtZW50c1R5cGVMaXN0EkwKGWV4Y2x1ZGVkU2VydmljZXNGcm9tVXNhZ2UYAiADKAsyKS5ibHVlYXBpLmFwaS5hd3MuRXhjbHVkZWRTZXJ2aWNlRnJvbVVzYWdlQmIKHWNsb3VkLmFscGhhdXMuYmx1ZWFwaS5hcGkuYXdzQhVBcGlBd3NDYWxjdWxhdG9yUHJvdG9aKmdpdGh1Yi5jb20vYWxwaGF1c2xhYnMvYmx1ZS1zZGstZ28vYXBpL2F3c2IGcHJvdG8z");
/**
 * Describes the message blueapi.api.aws.AccountMonthlyCostCalculated.
 * Use `create(AccountMonthlyCostCalculatedSchema)` to create a new message.
 */
exports.AccountMonthlyCostCalculatedSchema = (0, codegenv2_1.messageDesc)(exports.file_api_aws_calculator, 0);
/**
 * Describes the message blueapi.api.aws.AdjustmentsTypeList.
 * Use `create(AdjustmentsTypeListSchema)` to create a new message.
 */
exports.AdjustmentsTypeListSchema = (0, codegenv2_1.messageDesc)(exports.file_api_aws_calculator, 1);
/**
 * Describes the message blueapi.api.aws.ExcludedServiceFromUsage.
 * Use `create(ExcludedServiceFromUsageSchema)` to create a new message.
 */
exports.ExcludedServiceFromUsageSchema = (0, codegenv2_1.messageDesc)(exports.file_api_aws_calculator, 2);
/**
 * Describes the message blueapi.api.aws.CalculatorConfig.
 * Use `create(CalculatorConfigSchema)` to create a new message.
 */
exports.CalculatorConfigSchema = (0, codegenv2_1.messageDesc)(exports.file_api_aws_calculator, 3);
