// @generated by protoc-gen-es v2.7.0
// @generated from file protos/operation.proto (package protos, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Any } from "@bufbuild/protobuf/wkt";
import type { Status } from "../google/rpc/status_pb";

/**
 * Describes the file protos/operation.proto.
 */
export declare const file_protos_operation: GenFile;

/**
 * This resource represents a long-running operation that is the result of a
 * network API call.
 *
 * @generated from message protos.Operation
 */
export declare type Operation = Message<"protos.Operation"> & {
  /**
   * The server-assigned name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Service-specific metadata associated with the operation. It typically
   * contains progress information and common metadata such as create time.
   * Some services might not provide such metadata. Any method that returns a
   * long-running operation should document the metadata type, if any.
   *
   * @generated from field: google.protobuf.Any metadata = 2;
   */
  metadata?: Any;

  /**
   * If the value is `false`, it means the operation is still in progress.
   * If `true`, the operation is completed, and either `error` or `response` is
   * available.
   *
   * @generated from field: bool done = 3;
   */
  done: boolean;

  /**
   * The operation result, which can be either an `error` or a valid `response`.
   * If `done` == `false`, neither `error` nor `response` is set.
   * If `done` == `true`, exactly one of `error` or `response` is set.
   *
   * @generated from oneof protos.Operation.result
   */
  result: {
    /**
     * The error result of the operation in case of failure or cancellation.
     *
     * @generated from field: google.rpc.Status error = 4;
     */
    value: Status;
    case: "error";
  } | {
    /**
     * The normal response of the operation in case of success. If the original method returns
     * no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the
     * original method is standard `Get`/`Create`/`Update`, the response should be the
     * resource. For other methods, the response should have the type `XxxResponse`, where
     * `Xxx` is the original method name. For example, if the original method name is
     * `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.
     *
     * @generated from field: google.protobuf.Any response = 5;
     */
    value: Any;
    case: "response";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message protos.Operation.
 * Use `create(OperationSchema)` to create a new message.
 */
export declare const OperationSchema: GenMessage<Operation>;

/**
 * @generated from message protos.OperationImportCurMetadataV1
 */
export declare type OperationImportCurMetadataV1 = Message<"protos.OperationImportCurMetadataV1"> & {
  /**
   * @generated from field: string month = 1;
   */
  month: string;

  /**
   * @generated from field: repeated string accounts = 2;
   */
  accounts: string[];

  /**
   * @generated from field: string created = 3;
   */
  created: string;

  /**
   * @generated from field: string updated = 4;
   */
  updated: string;
};

/**
 * Describes the message protos.OperationImportCurMetadataV1.
 * Use `create(OperationImportCurMetadataV1Schema)` to create a new message.
 */
export declare const OperationImportCurMetadataV1Schema: GenMessage<OperationImportCurMetadataV1>;

/**
 * @generated from message protos.OperationAwsCalculateCostsMetadataV1
 */
export declare type OperationAwsCalculateCostsMetadataV1 = Message<"protos.OperationAwsCalculateCostsMetadataV1"> & {
  /**
   * Organization id.
   *
   * @generated from field: string orgId = 1;
   */
  orgId: string;

  /**
   * The month being calculated.
   *
   * @generated from field: string month = 2;
   */
  month: string;

  /**
   * If the request is for a specific group(s) (billing groups at the moment),
   * their equivalent ids are listed here. Otherwise, empty.
   *
   * @generated from field: repeated string groupIds = 3;
   */
  groupIds: string[];

  /**
   * Latest status information.
   *
   * @generated from field: string status = 4;
   */
  status: string;

  /**
   * Timestamp when operation was created/started in RFC3339 format.
   *
   * @generated from field: string created = 5;
   */
  created: string;

  /**
   * Timestamp of the operation's last update in RFC3339 format.
   *
   * @generated from field: string updated = 6;
   */
  updated: string;
};

/**
 * Describes the message protos.OperationAwsCalculateCostsMetadataV1.
 * Use `create(OperationAwsCalculateCostsMetadataV1Schema)` to create a new message.
 */
export declare const OperationAwsCalculateCostsMetadataV1Schema: GenMessage<OperationAwsCalculateCostsMetadataV1>;

/**
 * @generated from message protos.OperationAwsDiscoverAssetsMetadataV1
 */
export declare type OperationAwsDiscoverAssetsMetadataV1 = Message<"protos.OperationAwsDiscoverAssetsMetadataV1"> & {
  /**
   * @generated from field: repeated string accounts = 1;
   */
  accounts: string[];

  /**
   * @generated from field: repeated string services = 2;
   */
  services: string[];
};

/**
 * Describes the message protos.OperationAwsDiscoverAssetsMetadataV1.
 * Use `create(OperationAwsDiscoverAssetsMetadataV1Schema)` to create a new message.
 */
export declare const OperationAwsDiscoverAssetsMetadataV1Schema: GenMessage<OperationAwsDiscoverAssetsMetadataV1>;

