// @generated by protoc-gen-es v2.7.0
// @generated from file protos/operation.proto (package protos, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_rpc_status } from "../google/rpc/status_pb";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file protos/operation.proto.
 */
export const file_protos_operation = /*@__PURE__*/
  fileDesc("ChZwcm90b3Mvb3BlcmF0aW9uLnByb3RvEgZwcm90b3MiqAEKCU9wZXJhdGlvbhIMCgRuYW1lGAEgASgJEiYKCG1ldGFkYXRhGAIgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueRIMCgRkb25lGAMgASgIEiMKBWVycm9yGAQgASgLMhIuZ29vZ2xlLnJwYy5TdGF0dXNIABIoCghyZXNwb25zZRgFIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnlIAEIICgZyZXN1bHQiYQocT3BlcmF0aW9uSW1wb3J0Q3VyTWV0YWRhdGFWMRINCgVtb250aBgBIAEoCRIQCghhY2NvdW50cxgCIAMoCRIPCgdjcmVhdGVkGAMgASgJEg8KB3VwZGF0ZWQYBCABKAkiiAEKJE9wZXJhdGlvbkF3c0NhbGN1bGF0ZUNvc3RzTWV0YWRhdGFWMRINCgVvcmdJZBgBIAEoCRINCgVtb250aBgCIAEoCRIQCghncm91cElkcxgDIAMoCRIOCgZzdGF0dXMYBCABKAkSDwoHY3JlYXRlZBgFIAEoCRIPCgd1cGRhdGVkGAYgASgJIkoKJE9wZXJhdGlvbkF3c0Rpc2NvdmVyQXNzZXRzTWV0YWRhdGFWMRIQCghhY2NvdW50cxgBIAMoCRIQCghzZXJ2aWNlcxgCIAMoCUJLChRjbG91ZC5hbHBoYXVzLnByb3Rvc0IOT3BlcmF0aW9uUHJvdG9aI2dpdGh1Yi5jb20vYWxwaGF1c2xhYnMvdG9iZXJlcGxhY2VkYgZwcm90bzM", [file_google_rpc_status, file_google_protobuf_any]);

/**
 * Describes the message protos.Operation.
 * Use `create(OperationSchema)` to create a new message.
 */
export const OperationSchema = /*@__PURE__*/
  messageDesc(file_protos_operation, 0);

/**
 * Describes the message protos.OperationImportCurMetadataV1.
 * Use `create(OperationImportCurMetadataV1Schema)` to create a new message.
 */
export const OperationImportCurMetadataV1Schema = /*@__PURE__*/
  messageDesc(file_protos_operation, 1);

/**
 * Describes the message protos.OperationAwsCalculateCostsMetadataV1.
 * Use `create(OperationAwsCalculateCostsMetadataV1Schema)` to create a new message.
 */
export const OperationAwsCalculateCostsMetadataV1Schema = /*@__PURE__*/
  messageDesc(file_protos_operation, 2);

/**
 * Describes the message protos.OperationAwsDiscoverAssetsMetadataV1.
 * Use `create(OperationAwsDiscoverAssetsMetadataV1Schema)` to create a new message.
 */
export const OperationAwsDiscoverAssetsMetadataV1Schema = /*@__PURE__*/
  messageDesc(file_protos_operation, 3);

