// @generated by protoc-gen-es v2.7.0
// @generated from file pricing/v1/pricing.proto (package blueapi.pricing.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_api_pricing_details } from "../../api/pricing/details_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_protoc_gen_openapiv2_options_annotations } from "../../protoc-gen-openapiv2/options/annotations_pb";

/**
 * Describes the file pricing/v1/pricing.proto.
 */
export const file_pricing_v1_pricing = /*@__PURE__*/
  fileDesc("ChhwcmljaW5nL3YxL3ByaWNpbmcucHJvdG8SEmJsdWVhcGkucHJpY2luZy52MSIQCg5HZXRJbmZvUmVxdWVzdCIjCg9HZXRJbmZvUmVzcG9uc2USEAoIcmVzcG9uc2UYASABKAki2QEKEUdldFByaWNpbmdSZXF1ZXN0Eg4KBnZlbmRvchgBIAEoCRIPCgdzZXJ2aWNlGAIgASgJEg4KBnJlZ2lvbhgDIAEoCRINCgV0b2tlbhgEIAEoCRJDCgdmaWx0ZXJzGAYgAygLMjIuYmx1ZWFwaS5wcmljaW5nLnYxLkdldFByaWNpbmdSZXF1ZXN0LkZpbHRlcnNFbnRyeRIPCgdjb2x1bW5zGAUgAygJGi4KDEZpbHRlcnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIloKEkdldFByaWNpbmdSZXNwb25zZRINCgV0b2tlbhgBIAEoCRI1CgtwcmljaW5nRGF0YRgCIAMoCzIgLmJsdWVhcGkuYXBpLnByaWNpbmcuUHJpY2luZ0RhdGEiLQobR2V0U3VwcG9ydGVkU2VydmljZXNSZXF1ZXN0Eg4KBnZlbmRvchgBIAEoCSJfChxHZXRTdXBwb3J0ZWRTZXJ2aWNlc1Jlc3BvbnNlEj8KEXN1cHBvcnRlZFNlcnZpY2VzGAEgAygLMiQuYmx1ZWFwaS5wcmljaW5nLnYxLlN1cHBvcnRlZFNlcnZpY2UieAoQU3VwcG9ydGVkU2VydmljZRIPCgdzZXJ2aWNlGAEgASgJEg8KB3JlZ2lvbnMYAiADKAkSMQoKYXR0cmlidXRlcxgDIAMoCzIdLmJsdWVhcGkucHJpY2luZy52MS5BdHRyaWJ1dGUSDwoHY29sdW1ucxgEIAMoCSIoCglBdHRyaWJ1dGUSCwoDa2V5GAEgASgJEg4KBnZhbHVlcxgCIAMoCTKoBAoHUHJpY2luZxJkCgdHZXRJbmZvEiIuYmx1ZWFwaS5wcmljaW5nLnYxLkdldEluZm9SZXF1ZXN0GiMuYmx1ZWFwaS5wcmljaW5nLnYxLkdldEluZm9SZXNwb25zZSIQgtPkkwIKEggvdjAvaW5mbxJ8CgpHZXRQcmljaW5nEiUuYmx1ZWFwaS5wcmljaW5nLnYxLkdldFByaWNpbmdSZXF1ZXN0GiYuYmx1ZWFwaS5wcmljaW5nLnYxLkdldFByaWNpbmdSZXNwb25zZSIfgtPkkwIZOgEqIhQvdjAve3ZlbmRvcn0vcHJpY2luZxKYAQoUR2V0U3VwcG9ydGVkU2VydmljZXMSLy5ibHVlYXBpLnByaWNpbmcudjEuR2V0U3VwcG9ydGVkU2VydmljZXNSZXF1ZXN0GjAuYmx1ZWFwaS5wcmljaW5nLnYxLkdldFN1cHBvcnRlZFNlcnZpY2VzUmVzcG9uc2UiHYLT5JMCFxIVL3YwL3t2ZW5kb3J9L3NlcnZpY2VzGp0BkkGZARJGKEJFVEEpIFByaWNpbmcgQVBJLiBCYXNlIFVSTDogaHR0cHM6Ly9hcGkuYWxwaGF1cy5jbG91ZC9tL2JsdWUvcHJpY2luZxpPChJTZXJ2aWNlIGRlZmluaXRpb24SOWh0dHBzOi8vZ2l0aHViLmNvbS9hbHBoYXVzbGFicy9ibHVlYXBpL3RyZWUvbWFpbi9wcmljaW5nL0JRChljbG91ZC5hbHBoYXVzLmFwaS5wcmljaW5nQgxQcmljaW5nUHJvdG9aJmdpdGh1Yi5jb20vYWxwaGF1c2xhYnMvYmx1ZWFwaS9wcmljaW5nYgZwcm90bzM", [file_api_pricing_details, file_google_api_annotations, file_protoc_gen_openapiv2_options_annotations]);

/**
 * Describes the message blueapi.pricing.v1.GetInfoRequest.
 * Use `create(GetInfoRequestSchema)` to create a new message.
 */
export const GetInfoRequestSchema = /*@__PURE__*/
  messageDesc(file_pricing_v1_pricing, 0);

/**
 * Describes the message blueapi.pricing.v1.GetInfoResponse.
 * Use `create(GetInfoResponseSchema)` to create a new message.
 */
export const GetInfoResponseSchema = /*@__PURE__*/
  messageDesc(file_pricing_v1_pricing, 1);

/**
 * Describes the message blueapi.pricing.v1.GetPricingRequest.
 * Use `create(GetPricingRequestSchema)` to create a new message.
 */
export const GetPricingRequestSchema = /*@__PURE__*/
  messageDesc(file_pricing_v1_pricing, 2);

/**
 * Describes the message blueapi.pricing.v1.GetPricingResponse.
 * Use `create(GetPricingResponseSchema)` to create a new message.
 */
export const GetPricingResponseSchema = /*@__PURE__*/
  messageDesc(file_pricing_v1_pricing, 3);

/**
 * Describes the message blueapi.pricing.v1.GetSupportedServicesRequest.
 * Use `create(GetSupportedServicesRequestSchema)` to create a new message.
 */
export const GetSupportedServicesRequestSchema = /*@__PURE__*/
  messageDesc(file_pricing_v1_pricing, 4);

/**
 * Describes the message blueapi.pricing.v1.GetSupportedServicesResponse.
 * Use `create(GetSupportedServicesResponseSchema)` to create a new message.
 */
export const GetSupportedServicesResponseSchema = /*@__PURE__*/
  messageDesc(file_pricing_v1_pricing, 5);

/**
 * Describes the message blueapi.pricing.v1.SupportedService.
 * Use `create(SupportedServiceSchema)` to create a new message.
 */
export const SupportedServiceSchema = /*@__PURE__*/
  messageDesc(file_pricing_v1_pricing, 6);

/**
 * Describes the message blueapi.pricing.v1.Attribute.
 * Use `create(AttributeSchema)` to create a new message.
 */
export const AttributeSchema = /*@__PURE__*/
  messageDesc(file_pricing_v1_pricing, 7);

/**
 * Pricing service definition.
 *
 * @generated from service blueapi.pricing.v1.Pricing
 */
export const Pricing = /*@__PURE__*/
  serviceDesc(file_pricing_v1_pricing, 0);

