// @generated by protoc-gen-es v2.7.0
// @generated from file api/ripple/v1/export.proto (package blueapi.api.ripple.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/ripple/v1/export.proto.
 */
export declare const file_api_ripple_v1_export: GenFile;

/**
 * ExportData resource definition.
 *
 * @generated from message blueapi.api.ripple.v1.ExportData
 */
export declare type ExportData = Message<"blueapi.api.ripple.v1.ExportData"> & {
  /**
   * Base64 encoded value.
   *
   * @generated from field: string content = 1;
   */
  content: string;

  /**
   * Downloaded content lines.
   *
   * @generated from field: int64 downloadedRows = 2;
   */
  downloadedRows: bigint;

  /**
   * Total of content lines.
   *
   * @generated from field: int64 totalRows = 3;
   */
  totalRows: bigint;
};

/**
 * Describes the message blueapi.api.ripple.v1.ExportData.
 * Use `create(ExportDataSchema)` to create a new message.
 */
export declare const ExportDataSchema: GenMessage<ExportData>;

