// @generated by protoc-gen-es v2.7.0
// @generated from file api/cover/attribute.proto (package blueapi.api.cover, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/cover/attribute.proto.
 */
export declare const file_api_cover_attribute: GenFile;

/**
 * @generated from message blueapi.api.cover.Category
 */
export declare type Category = Message<"blueapi.api.cover.Category"> & {
  /**
   * @generated from field: string display = 1;
   */
  display: string;

  /**
   * @generated from field: string query = 2;
   */
  query: string;
};

/**
 * Describes the message blueapi.api.cover.Category.
 * Use `create(CategorySchema)` to create a new message.
 */
export declare const CategorySchema: GenMessage<Category>;

/**
 * @generated from message blueapi.api.cover.Result
 */
export declare type Result = Message<"blueapi.api.cover.Result"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message blueapi.api.cover.Result.
 * Use `create(ResultSchema)` to create a new message.
 */
export declare const ResultSchema: GenMessage<Result>;

