// @generated by protoc-gen-es v2.7.0
// @generated from file api/cover/optimizationrecommendation.proto (package blueapi.api.cover, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/cover/optimizationrecommendation.proto.
 */
export declare const file_api_cover_optimizationrecommendation: GenFile;

/**
 * @generated from message blueapi.api.cover.ExecutedRecommendationDetails
 */
export declare type ExecutedRecommendationDetails = Message<"blueapi.api.cover.ExecutedRecommendationDetails"> & {
  /**
   * @generated from field: string recommendationId = 1;
   */
  recommendationId: string;

  /**
   * @generated from field: string recommendaton = 2;
   */
  recommendaton: string;

  /**
   * @generated from field: string target = 3;
   */
  target: string;

  /**
   * @generated from field: string accountName = 4;
   */
  accountName: string;

  /**
   * @generated from field: string service = 5;
   */
  service: string;

  /**
   * @generated from field: string completedDate = 6;
   */
  completedDate: string;

  /**
   * @generated from field: double estSavings = 7;
   */
  estSavings: number;

  /**
   * @generated from field: double estCost = 8;
   */
  estCost: number;

  /**
   * @generated from field: string vendor = 9;
   */
  vendor: string;

  /**
   * @generated from field: string category = 10;
   */
  category: string;

  /**
   * @generated from field: string dateAdded = 11;
   */
  dateAdded: string;

  /**
   * @generated from field: string personInCharge = 12;
   */
  personInCharge: string;

  /**
   * @generated from field: string optimizationStatus = 13;
   */
  optimizationStatus: string;
};

/**
 * Describes the message blueapi.api.cover.ExecutedRecommendationDetails.
 * Use `create(ExecutedRecommendationDetailsSchema)` to create a new message.
 */
export declare const ExecutedRecommendationDetailsSchema: GenMessage<ExecutedRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.AWSRecommendations
 */
export declare type AWSRecommendations = Message<"blueapi.api.cover.AWSRecommendations"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string accountId = 2;
   */
  accountId: string;

  /**
   * @generated from field: string accountName = 3;
   */
  accountName: string;

  /**
   * @generated from field: string instanceId = 4;
   */
  instanceId: string;

  /**
   * @generated from field: string instanceName = 5;
   */
  instanceName: string;

  /**
   * @generated from field: string service = 6;
   */
  service: string;

  /**
   * @generated from field: string source = 7;
   */
  source: string;

  /**
   * @generated from field: string costGroup = 8;
   */
  costGroup: string;

  /**
   * @generated from field: string recommendation = 9;
   */
  recommendation: string;

  /**
   * @generated from field: string region = 10;
   */
  region: string;

  /**
   * @generated from field: double estsavings = 11;
   */
  estsavings: number;

  /**
   * @generated from field: double estcost = 12;
   */
  estcost: number;

  /**
   * @generated from field: double estsavingsPercentage = 13;
   */
  estsavingsPercentage: number;

  /**
   * @generated from field: string resourceArn = 14;
   */
  resourceArn: string;

  /**
   * @generated from field: bool restartNeeded = 15;
   */
  restartNeeded: boolean;

  /**
   * @generated from field: bool rollbackPossible = 16;
   */
  rollbackPossible: boolean;

  /**
   * @generated from field: string lastUpdatedAt = 17;
   */
  lastUpdatedAt: string;

  /**
   * @generated from field: string recommendationGroup = 26;
   */
  recommendationGroup: string;

  /**
   * @generated from field: string category = 27;
   */
  category: string;

  /**
   * @generated from field: blueapi.api.cover.PurchaseRIRecommendationDetails purchaseRIRecommendationDetails = 18;
   */
  purchaseRIRecommendationDetails?: PurchaseRIRecommendationDetails;

  /**
   * @generated from field: blueapi.api.cover.SavingsPlanRecommendationDetails savingsPlanRecommendationDetails = 19;
   */
  savingsPlanRecommendationDetails?: SavingsPlanRecommendationDetails;

  /**
   * @generated from field: blueapi.api.cover.RightSizingRecommendationDetails rightSizingRecommendationDetails = 20;
   */
  rightSizingRecommendationDetails?: RightSizingRecommendationDetails;

  /**
   * @generated from field: blueapi.api.cover.UpgradeRecommendationDetails upgradeRecommendationDetails = 21;
   */
  upgradeRecommendationDetails?: UpgradeRecommendationDetails;

  /**
   * @generated from field: blueapi.api.cover.MigrateRecommendationDetails migrateRecommendationDetails = 22;
   */
  migrateRecommendationDetails?: MigrateRecommendationDetails;

  /**
   * @generated from field: blueapi.api.cover.StopInstanceRecommendationDetails stopInstanceRecommendationDetails = 23;
   */
  stopInstanceRecommendationDetails?: StopInstanceRecommendationDetails;

  /**
   * @generated from field: blueapi.api.cover.DeleteRecommendationDetails deleteRecommendationDetails = 24;
   */
  deleteRecommendationDetails?: DeleteRecommendationDetails;

  /**
   * @generated from field: blueapi.api.cover.OtherRecommendationDetails otherRecommendationDetails = 25;
   */
  otherRecommendationDetails?: OtherRecommendationDetails;
};

/**
 * Describes the message blueapi.api.cover.AWSRecommendations.
 * Use `create(AWSRecommendationsSchema)` to create a new message.
 */
export declare const AWSRecommendationsSchema: GenMessage<AWSRecommendations>;

/**
 * @generated from message blueapi.api.cover.PurchaseRIRecommendationDetails
 */
export declare type PurchaseRIRecommendationDetails = Message<"blueapi.api.cover.PurchaseRIRecommendationDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.EC2Details ec2Options = 1;
   */
  ec2Options?: EC2Details;

  /**
   * @generated from field: blueapi.api.cover.ElasticCacheDetails elasticCacheOptions = 2;
   */
  elasticCacheOptions?: ElasticCacheDetails;

  /**
   * @generated from field: blueapi.api.cover.ESDetails esOptions = 3;
   */
  esOptions?: ESDetails;

  /**
   * @generated from field: blueapi.api.cover.RDSDetails rdsOptions = 4;
   */
  rdsOptions?: RDSDetails;

  /**
   * @generated from field: blueapi.api.cover.RedshiftDetails redshiftOptions = 5;
   */
  redshiftOptions?: RedshiftDetails;

  /**
   * @generated from field: blueapi.api.cover.MemoryDBDetails memoryDbOptions = 19;
   */
  memoryDbOptions?: MemoryDBDetails;

  /**
   * @generated from field: int32 recommendedNormalizedUnits = 6;
   */
  recommendedNormalizedUnits: number;

  /**
   * @generated from field: int32 recommendedNumberOfInstanceToPurchase = 7;
   */
  recommendedNumberOfInstanceToPurchase: number;

  /**
   * @generated from field: string paymentOption = 8;
   */
  paymentOption: string;

  /**
   * @generated from field: string offeringClass = 9;
   */
  offeringClass: string;

  /**
   * @generated from field: string term = 10;
   */
  term: string;

  /**
   * @generated from field: double upfrontCost = 11;
   */
  upfrontCost: number;

  /**
   * @generated from field: string instanceType = 12;
   */
  instanceType: string;

  /**
   * @generated from field: string platform = 13;
   */
  platform: string;

  /**
   * @generated from field: string region = 14;
   */
  region: string;

  /**
   * @generated from field: bool sizeFlexEligible = 15;
   */
  sizeFlexEligible: boolean;

  /**
   * @generated from field: string tenancy = 16;
   */
  tenancy: string;

  /**
   * @generated from field: bool currentGeneration = 17;
   */
  currentGeneration: boolean;

  /**
   * @generated from field: blueapi.api.cover.EstOutcomeFromPurchaseRIRecommendation estOutcomeFromPurchaseRIRecommendation = 18;
   */
  estOutcomeFromPurchaseRIRecommendation?: EstOutcomeFromPurchaseRIRecommendation;
};

/**
 * Describes the message blueapi.api.cover.PurchaseRIRecommendationDetails.
 * Use `create(PurchaseRIRecommendationDetailsSchema)` to create a new message.
 */
export declare const PurchaseRIRecommendationDetailsSchema: GenMessage<PurchaseRIRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.EstOutcomeFromPurchaseRIRecommendation
 */
export declare type EstOutcomeFromPurchaseRIRecommendation = Message<"blueapi.api.cover.EstOutcomeFromPurchaseRIRecommendation"> & {
  /**
   * @generated from field: double aveUtilization = 1;
   */
  aveUtilization: number;

  /**
   * @generated from field: double aveNormalizedUnitsUsedPerHour = 2;
   */
  aveNormalizedUnitsUsedPerHour: number;

  /**
   * @generated from field: double aveNumberofInstanceUsedPerHour = 3;
   */
  aveNumberofInstanceUsedPerHour: number;

  /**
   * @generated from field: double breakEvenInMonths = 4;
   */
  breakEvenInMonths: number;

  /**
   * @generated from field: double monthlyOnDemandCost = 5;
   */
  monthlyOnDemandCost: number;

  /**
   * @generated from field: double monthlyRICost = 6;
   */
  monthlyRICost: number;

  /**
   * @generated from field: double monthlySavings = 7;
   */
  monthlySavings: number;

  /**
   * @generated from field: double monthlySavingsPercentage = 8;
   */
  monthlySavingsPercentage: number;

  /**
   * @generated from field: double maxNormalizedUnitsUsedPerHour = 9;
   */
  maxNormalizedUnitsUsedPerHour: number;

  /**
   * @generated from field: double maxNumberOfInstanceUsedPerHour = 10;
   */
  maxNumberOfInstanceUsedPerHour: number;

  /**
   * @generated from field: double minNormalizedUnitsUsedPerHour = 11;
   */
  minNormalizedUnitsUsedPerHour: number;

  /**
   * @generated from field: double minNumberOfInstanceUsedPerHour = 12;
   */
  minNumberOfInstanceUsedPerHour: number;
};

/**
 * Describes the message blueapi.api.cover.EstOutcomeFromPurchaseRIRecommendation.
 * Use `create(EstOutcomeFromPurchaseRIRecommendationSchema)` to create a new message.
 */
export declare const EstOutcomeFromPurchaseRIRecommendationSchema: GenMessage<EstOutcomeFromPurchaseRIRecommendation>;

/**
 * @generated from message blueapi.api.cover.MemoryDBDetails
 */
export declare type MemoryDBDetails = Message<"blueapi.api.cover.MemoryDBDetails"> & {
  /**
   * @generated from field: string family = 1;
   */
  family: string;

  /**
   * @generated from field: string nodeType = 2;
   */
  nodeType: string;
};

/**
 * Describes the message blueapi.api.cover.MemoryDBDetails.
 * Use `create(MemoryDBDetailsSchema)` to create a new message.
 */
export declare const MemoryDBDetailsSchema: GenMessage<MemoryDBDetails>;

/**
 * @generated from message blueapi.api.cover.EC2Details
 */
export declare type EC2Details = Message<"blueapi.api.cover.EC2Details"> & {
  /**
   * @generated from field: string instanceType = 1;
   */
  instanceType: string;

  /**
   * @generated from field: string tenancy = 2;
   */
  tenancy: string;

  /**
   * @generated from field: string family = 3;
   */
  family: string;

  /**
   * @generated from field: string platform = 4;
   */
  platform: string;
};

/**
 * Describes the message blueapi.api.cover.EC2Details.
 * Use `create(EC2DetailsSchema)` to create a new message.
 */
export declare const EC2DetailsSchema: GenMessage<EC2Details>;

/**
 * @generated from message blueapi.api.cover.ElasticCacheDetails
 */
export declare type ElasticCacheDetails = Message<"blueapi.api.cover.ElasticCacheDetails"> & {
  /**
   * @generated from field: bool currentGeneration = 1;
   */
  currentGeneration: boolean;

  /**
   * @generated from field: string nodeType = 2;
   */
  nodeType: string;

  /**
   * @generated from field: string family = 3;
   */
  family: string;
};

/**
 * Describes the message blueapi.api.cover.ElasticCacheDetails.
 * Use `create(ElasticCacheDetailsSchema)` to create a new message.
 */
export declare const ElasticCacheDetailsSchema: GenMessage<ElasticCacheDetails>;

/**
 * @generated from message blueapi.api.cover.ESDetails
 */
export declare type ESDetails = Message<"blueapi.api.cover.ESDetails"> & {
  /**
   * @generated from field: bool currentGeneration = 1;
   */
  currentGeneration: boolean;

  /**
   * @generated from field: string instanceClass = 2;
   */
  instanceClass: string;

  /**
   * @generated from field: string instanceSize = 3;
   */
  instanceSize: string;
};

/**
 * Describes the message blueapi.api.cover.ESDetails.
 * Use `create(ESDetailsSchema)` to create a new message.
 */
export declare const ESDetailsSchema: GenMessage<ESDetails>;

/**
 * @generated from message blueapi.api.cover.RDSDetails
 */
export declare type RDSDetails = Message<"blueapi.api.cover.RDSDetails"> & {
  /**
   * @generated from field: string dbEdition = 1;
   */
  dbEdition: string;

  /**
   * @generated from field: string dbEngine = 2;
   */
  dbEngine: string;

  /**
   * @generated from field: string deploymentOptions = 3;
   */
  deploymentOptions: string;

  /**
   * @generated from field: string family = 4;
   */
  family: string;

  /**
   * @generated from field: string instanceType = 5;
   */
  instanceType: string;

  /**
   * @generated from field: string licenseModel = 6;
   */
  licenseModel: string;
};

/**
 * Describes the message blueapi.api.cover.RDSDetails.
 * Use `create(RDSDetailsSchema)` to create a new message.
 */
export declare const RDSDetailsSchema: GenMessage<RDSDetails>;

/**
 * @generated from message blueapi.api.cover.RedshiftDetails
 */
export declare type RedshiftDetails = Message<"blueapi.api.cover.RedshiftDetails"> & {
  /**
   * @generated from field: bool currentGeneration = 1;
   */
  currentGeneration: boolean;

  /**
   * @generated from field: string nodeType = 2;
   */
  nodeType: string;

  /**
   * @generated from field: string family = 3;
   */
  family: string;
};

/**
 * Describes the message blueapi.api.cover.RedshiftDetails.
 * Use `create(RedshiftDetailsSchema)` to create a new message.
 */
export declare const RedshiftDetailsSchema: GenMessage<RedshiftDetails>;

/**
 * @generated from message blueapi.api.cover.SavingsPlanRecommendationDetails
 */
export declare type SavingsPlanRecommendationDetails = Message<"blueapi.api.cover.SavingsPlanRecommendationDetails"> & {
  /**
   * @generated from field: string currencyCode = 1;
   */
  currencyCode: string;

  /**
   * @generated from field: double hourlyCommitmentToPurchase = 2;
   */
  hourlyCommitmentToPurchase: number;

  /**
   * @generated from field: string offeringId = 3;
   */
  offeringId: string;

  /**
   * @generated from field: string paymentOption = 4;
   */
  paymentOption: string;

  /**
   * @generated from field: string savingsPlanType = 5;
   */
  savingsPlanType: string;

  /**
   * @generated from field: string term = 6;
   */
  term: string;

  /**
   * @generated from field: double upfrontCost = 7;
   */
  upfrontCost: number;

  /**
   * @generated from field: blueapi.api.cover.SPCurrentUtilizationDetails currentUtilizationDetails = 8;
   */
  currentUtilizationDetails?: SPCurrentUtilizationDetails;

  /**
   * @generated from field: blueapi.api.cover.EstOutcomeFromSPRecommendation estOutcomeFromSPRecommendation = 9;
   */
  estOutcomeFromSPRecommendation?: EstOutcomeFromSPRecommendation;
};

/**
 * Describes the message blueapi.api.cover.SavingsPlanRecommendationDetails.
 * Use `create(SavingsPlanRecommendationDetailsSchema)` to create a new message.
 */
export declare const SavingsPlanRecommendationDetailsSchema: GenMessage<SavingsPlanRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.SPCurrentUtilizationDetails
 */
export declare type SPCurrentUtilizationDetails = Message<"blueapi.api.cover.SPCurrentUtilizationDetails"> & {
  /**
   * @generated from field: double aveCoverage = 1;
   */
  aveCoverage: number;

  /**
   * @generated from field: double aveHourOnDemandSpend = 2;
   */
  aveHourOnDemandSpend: number;

  /**
   * @generated from field: double maxHourlyOndemandSpend = 3;
   */
  maxHourlyOndemandSpend: number;

  /**
   * @generated from field: double minHourlyOndemandSpend = 4;
   */
  minHourlyOndemandSpend: number;

  /**
   * @generated from field: double existingHourlyCommitment = 5;
   */
  existingHourlyCommitment: number;

  /**
   * @generated from field: double estOnDemandCostWithHourlyCommitment = 6;
   */
  estOnDemandCostWithHourlyCommitment: number;
};

/**
 * Describes the message blueapi.api.cover.SPCurrentUtilizationDetails.
 * Use `create(SPCurrentUtilizationDetailsSchema)` to create a new message.
 */
export declare const SPCurrentUtilizationDetailsSchema: GenMessage<SPCurrentUtilizationDetails>;

/**
 * @generated from message blueapi.api.cover.EstOutcomeFromSPRecommendation
 */
export declare type EstOutcomeFromSPRecommendation = Message<"blueapi.api.cover.EstOutcomeFromSPRecommendation"> & {
  /**
   * @generated from field: double aveCoverage = 1;
   */
  aveCoverage: number;

  /**
   * @generated from field: double aveUtilization = 2;
   */
  aveUtilization: number;

  /**
   * @generated from field: double monthlySavingsAmount = 3;
   */
  monthlySavingsAmount: number;

  /**
   * @generated from field: double onDemandCost = 4;
   */
  onDemandCost: number;

  /**
   * @generated from field: double roi = 5;
   */
  roi: number;

  /**
   * @generated from field: double savingsPlanCost = 6;
   */
  savingsPlanCost: number;

  /**
   * @generated from field: double savingsPercentage = 7;
   */
  savingsPercentage: number;
};

/**
 * Describes the message blueapi.api.cover.EstOutcomeFromSPRecommendation.
 * Use `create(EstOutcomeFromSPRecommendationSchema)` to create a new message.
 */
export declare const EstOutcomeFromSPRecommendationSchema: GenMessage<EstOutcomeFromSPRecommendation>;

/**
 * @generated from message blueapi.api.cover.RightSizingRecommendationDetails
 */
export declare type RightSizingRecommendationDetails = Message<"blueapi.api.cover.RightSizingRecommendationDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.EC2rightSizingDetails ec2RightSizingDetails = 1;
   */
  ec2RightSizingDetails?: EC2rightSizingDetails;

  /**
   * @generated from field: blueapi.api.cover.LambdaRightSizingRecommendationDetails lambdaRightSizingRecommendationDetails = 2;
   */
  lambdaRightSizingRecommendationDetails?: LambdaRightSizingRecommendationDetails;

  /**
   * @generated from field: blueapi.api.cover.EBSDetails ebsRightSizingRecommendationDetails = 3;
   */
  ebsRightSizingRecommendationDetails?: EBSDetails;

  /**
   * @generated from field: blueapi.api.cover.EcsRightSizingRecommendationDetails ecsRightSizingRecommendationDetails = 4;
   */
  ecsRightSizingRecommendationDetails?: EcsRightSizingRecommendationDetails;

  /**
   * @generated from field: blueapi.api.cover.RDSRightsizingDetails rdsRightSizingRecommendationDetails = 7;
   */
  rdsRightSizingRecommendationDetails?: RDSRightsizingDetails;

  /**
   * @generated from field: double estimatedMonthlyCost = 5;
   */
  estimatedMonthlyCost: number;

  /**
   * @generated from field: double estimatedMonthlySavings = 6;
   */
  estimatedMonthlySavings: number;
};

/**
 * Describes the message blueapi.api.cover.RightSizingRecommendationDetails.
 * Use `create(RightSizingRecommendationDetailsSchema)` to create a new message.
 */
export declare const RightSizingRecommendationDetailsSchema: GenMessage<RightSizingRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.StopRDSDetails
 */
export declare type StopRDSDetails = Message<"blueapi.api.cover.StopRDSDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.RDSDBInstance rdsDBInstance = 1;
   */
  rdsDBInstance?: RDSDBInstance;
};

/**
 * Describes the message blueapi.api.cover.StopRDSDetails.
 * Use `create(StopRDSDetailsSchema)` to create a new message.
 */
export declare const StopRDSDetailsSchema: GenMessage<StopRDSDetails>;

/**
 * @generated from message blueapi.api.cover.MigrateRDSDetails
 */
export declare type MigrateRDSDetails = Message<"blueapi.api.cover.MigrateRDSDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.RDSDBInstance rdsDbInstance = 1;
   */
  rdsDbInstance?: RDSDBInstance;
};

/**
 * Describes the message blueapi.api.cover.MigrateRDSDetails.
 * Use `create(MigrateRDSDetailsSchema)` to create a new message.
 */
export declare const MigrateRDSDetailsSchema: GenMessage<MigrateRDSDetails>;

/**
 * @generated from message blueapi.api.cover.RDSUpgradeDetails
 */
export declare type RDSUpgradeDetails = Message<"blueapi.api.cover.RDSUpgradeDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.RDSDBInstance rdsDbInstance = 1;
   */
  rdsDbInstance?: RDSDBInstance;

  /**
   * @generated from field: blueapi.api.cover.RDSDBInstanceStorage rdsDbInstanceStorage = 2;
   */
  rdsDbInstanceStorage?: RDSDBInstanceStorage;
};

/**
 * Describes the message blueapi.api.cover.RDSUpgradeDetails.
 * Use `create(RDSUpgradeDetailsSchema)` to create a new message.
 */
export declare const RDSUpgradeDetailsSchema: GenMessage<RDSUpgradeDetails>;

/**
 * @generated from message blueapi.api.cover.RDSRightsizingDetails
 */
export declare type RDSRightsizingDetails = Message<"blueapi.api.cover.RDSRightsizingDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.RDSDBInstance rdsDbInstance = 1;
   */
  rdsDbInstance?: RDSDBInstance;

  /**
   * @generated from field: blueapi.api.cover.RDSDBInstanceStorage rdsDbInstanceStorage = 2;
   */
  rdsDbInstanceStorage?: RDSDBInstanceStorage;
};

/**
 * Describes the message blueapi.api.cover.RDSRightsizingDetails.
 * Use `create(RDSRightsizingDetailsSchema)` to create a new message.
 */
export declare const RDSRightsizingDetailsSchema: GenMessage<RDSRightsizingDetails>;

/**
 * @generated from message blueapi.api.cover.RDSDBInstance
 */
export declare type RDSDBInstance = Message<"blueapi.api.cover.RDSDBInstance"> & {
  /**
   * @generated from field: blueapi.api.cover.RDSDBInstance.Details currentDetails = 1;
   */
  currentDetails?: RDSDBInstance_Details;

  /**
   * @generated from field: blueapi.api.cover.RDSDBInstance.Details recommendationDetails = 2;
   */
  recommendationDetails?: RDSDBInstance_Details;

  /**
   * @generated from field: repeated blueapi.api.cover.UtilizationData cpuUtilization = 3;
   */
  cpuUtilization: UtilizationData[];
};

/**
 * Describes the message blueapi.api.cover.RDSDBInstance.
 * Use `create(RDSDBInstanceSchema)` to create a new message.
 */
export declare const RDSDBInstanceSchema: GenMessage<RDSDBInstance>;

/**
 * @generated from message blueapi.api.cover.RDSDBInstance.Details
 */
export declare type RDSDBInstance_Details = Message<"blueapi.api.cover.RDSDBInstance.Details"> & {
  /**
   * @generated from field: string instanceClass = 1;
   */
  instanceClass: string;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation costCalculation = 2;
   */
  costCalculation?: CostCalculation;
};

/**
 * Describes the message blueapi.api.cover.RDSDBInstance.Details.
 * Use `create(RDSDBInstance_DetailsSchema)` to create a new message.
 */
export declare const RDSDBInstance_DetailsSchema: GenMessage<RDSDBInstance_Details>;

/**
 * @generated from message blueapi.api.cover.RDSDBInstanceStorage
 */
export declare type RDSDBInstanceStorage = Message<"blueapi.api.cover.RDSDBInstanceStorage"> & {
  /**
   * @generated from field: blueapi.api.cover.RDSDBInstanceStorage.Details currentDetails = 1;
   */
  currentDetails?: RDSDBInstanceStorage_Details;

  /**
   * @generated from field: blueapi.api.cover.RDSDBInstanceStorage.Details recommendationDetails = 2;
   */
  recommendationDetails?: RDSDBInstanceStorage_Details;
};

/**
 * Describes the message blueapi.api.cover.RDSDBInstanceStorage.
 * Use `create(RDSDBInstanceStorageSchema)` to create a new message.
 */
export declare const RDSDBInstanceStorageSchema: GenMessage<RDSDBInstanceStorage>;

/**
 * @generated from message blueapi.api.cover.RDSDBInstanceStorage.Details
 */
export declare type RDSDBInstanceStorage_Details = Message<"blueapi.api.cover.RDSDBInstanceStorage.Details"> & {
  /**
   * @generated from field: double allocatedStorageInGb = 1;
   */
  allocatedStorageInGb: number;

  /**
   * @generated from field: double iops = 2;
   */
  iops: number;

  /**
   * @generated from field: double storageThroughput = 3;
   */
  storageThroughput: number;

  /**
   * @generated from field: string storageType = 4;
   */
  storageType: string;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation costCalculation = 5;
   */
  costCalculation?: CostCalculation;
};

/**
 * Describes the message blueapi.api.cover.RDSDBInstanceStorage.Details.
 * Use `create(RDSDBInstanceStorage_DetailsSchema)` to create a new message.
 */
export declare const RDSDBInstanceStorage_DetailsSchema: GenMessage<RDSDBInstanceStorage_Details>;

/**
 * @generated from message blueapi.api.cover.EC2rightSizingDetails
 */
export declare type EC2rightSizingDetails = Message<"blueapi.api.cover.EC2rightSizingDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.CurrentEC2Details currentEC2Details = 1;
   */
  currentEC2Details?: CurrentEC2Details;

  /**
   * @generated from field: blueapi.api.cover.EC2ModifyRecommendationDetails eC2ModifyRecommendationDetails = 2;
   */
  eC2ModifyRecommendationDetails?: EC2ModifyRecommendationDetails;
};

/**
 * Describes the message blueapi.api.cover.EC2rightSizingDetails.
 * Use `create(EC2rightSizingDetailsSchema)` to create a new message.
 */
export declare const EC2rightSizingDetailsSchema: GenMessage<EC2rightSizingDetails>;

/**
 * @generated from message blueapi.api.cover.CurrentEC2Details
 */
export declare type CurrentEC2Details = Message<"blueapi.api.cover.CurrentEC2Details"> & {
  /**
   * @generated from field: string instanceType = 1;
   */
  instanceType: string;

  /**
   * @generated from field: string os = 2;
   */
  os: string;

  /**
   * @generated from field: string region = 3;
   */
  region: string;

  /**
   * @generated from field: double cpuUtilization = 4;
   */
  cpuUtilization: number;

  /**
   * @generated from field: double memoryUtilization = 5;
   */
  memoryUtilization: number;

  /**
   * @generated from field: double diskUtilization = 6;
   */
  diskUtilization: number;

  /**
   * @generated from field: string networkCapacity = 7;
   */
  networkCapacity: string;

  /**
   * @generated from field: double monthlyCost = 8;
   */
  monthlyCost: number;

  /**
   * @generated from field: repeated blueapi.api.cover.UtilizationData eC2CpuUtilization = 9;
   */
  eC2CpuUtilization: UtilizationData[];

  /**
   * @generated from field: repeated blueapi.api.cover.UtilizationData eC2DiskUtilization = 10;
   */
  eC2DiskUtilization: UtilizationData[];

  /**
   * @generated from field: repeated blueapi.api.cover.UtilizationData eC2MemoryUtilization = 11;
   */
  eC2MemoryUtilization: UtilizationData[];

  /**
   * @generated from field: repeated blueapi.api.cover.UtilizationData networkTrafficData = 12;
   */
  networkTrafficData: UtilizationData[];

  /**
   * @generated from field: blueapi.api.cover.CurrentEC2Details.OtherDetails otherDetails = 13;
   */
  otherDetails?: CurrentEC2Details_OtherDetails;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation costCalculation = 14;
   */
  costCalculation?: CostCalculation;
};

/**
 * Describes the message blueapi.api.cover.CurrentEC2Details.
 * Use `create(CurrentEC2DetailsSchema)` to create a new message.
 */
export declare const CurrentEC2DetailsSchema: GenMessage<CurrentEC2Details>;

/**
 * @generated from message blueapi.api.cover.CurrentEC2Details.OtherDetails
 */
export declare type CurrentEC2Details_OtherDetails = Message<"blueapi.api.cover.CurrentEC2Details.OtherDetails"> & {
  /**
   * @generated from field: string exclusionStatus = 1;
   */
  exclusionStatus: string;

  /**
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: string resource = 3;
   */
  resource: string;

  /**
   * @generated from field: string awsConfigRule = 4;
   */
  awsConfigRule: string;

  /**
   * @generated from field: string inputParameters = 5;
   */
  inputParameters: string;
};

/**
 * Describes the message blueapi.api.cover.CurrentEC2Details.OtherDetails.
 * Use `create(CurrentEC2Details_OtherDetailsSchema)` to create a new message.
 */
export declare const CurrentEC2Details_OtherDetailsSchema: GenMessage<CurrentEC2Details_OtherDetails>;

/**
 * @generated from message blueapi.api.cover.EC2ModifyRecommendationDetails
 */
export declare type EC2ModifyRecommendationDetails = Message<"blueapi.api.cover.EC2ModifyRecommendationDetails"> & {
  /**
   * @generated from field: string instanceType = 1;
   */
  instanceType: string;

  /**
   * @generated from field: string os = 2;
   */
  os: string;

  /**
   * @generated from field: string region = 3;
   */
  region: string;

  /**
   * @generated from field: double cpuUtilization = 4;
   */
  cpuUtilization: number;

  /**
   * @generated from field: double memoryUtilization = 5;
   */
  memoryUtilization: number;

  /**
   * @generated from field: double diskUtilization = 6;
   */
  diskUtilization: number;

  /**
   * @generated from field: string networkCapacity = 7;
   */
  networkCapacity: string;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation costCalculation = 15;
   */
  costCalculation?: CostCalculation;
};

/**
 * Describes the message blueapi.api.cover.EC2ModifyRecommendationDetails.
 * Use `create(EC2ModifyRecommendationDetailsSchema)` to create a new message.
 */
export declare const EC2ModifyRecommendationDetailsSchema: GenMessage<EC2ModifyRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.UtilizationData
 */
export declare type UtilizationData = Message<"blueapi.api.cover.UtilizationData"> & {
  /**
   * @generated from field: string date = 1;
   */
  date: string;

  /**
   * @generated from field: float value = 2;
   */
  value: number;
};

/**
 * Describes the message blueapi.api.cover.UtilizationData.
 * Use `create(UtilizationDataSchema)` to create a new message.
 */
export declare const UtilizationDataSchema: GenMessage<UtilizationData>;

/**
 * @generated from message blueapi.api.cover.LambdaRightSizingRecommendationDetails
 */
export declare type LambdaRightSizingRecommendationDetails = Message<"blueapi.api.cover.LambdaRightSizingRecommendationDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.ResourceDetails lambdaCurrentConfiguration = 1;
   */
  lambdaCurrentConfiguration?: ResourceDetails;

  /**
   * @generated from field: blueapi.api.cover.ResourceDetails lambdaRecommendedConfiguration = 2;
   */
  lambdaRecommendedConfiguration?: ResourceDetails;
};

/**
 * Describes the message blueapi.api.cover.LambdaRightSizingRecommendationDetails.
 * Use `create(LambdaRightSizingRecommendationDetailsSchema)` to create a new message.
 */
export declare const LambdaRightSizingRecommendationDetailsSchema: GenMessage<LambdaRightSizingRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.EcsRightSizingRecommendationDetails
 */
export declare type EcsRightSizingRecommendationDetails = Message<"blueapi.api.cover.EcsRightSizingRecommendationDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.ResourceDetails EcsCurrentConfiguration = 1;
   */
  EcsCurrentConfiguration?: ResourceDetails;

  /**
   * @generated from field: blueapi.api.cover.ResourceDetails EcsRecommendedConfiguration = 2;
   */
  EcsRecommendedConfiguration?: ResourceDetails;
};

/**
 * Describes the message blueapi.api.cover.EcsRightSizingRecommendationDetails.
 * Use `create(EcsRightSizingRecommendationDetailsSchema)` to create a new message.
 */
export declare const EcsRightSizingRecommendationDetailsSchema: GenMessage<EcsRightSizingRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.ResourceDetails
 */
export declare type ResourceDetails = Message<"blueapi.api.cover.ResourceDetails"> & {
  /**
   * @generated from field: string architecture = 1;
   */
  architecture: string;

  /**
   * @generated from field: double memorysizeInMB = 2;
   */
  memorysizeInMB: number;

  /**
   * @generated from field: string platform = 3;
   */
  platform: string;

  /**
   * @generated from field: int32 vCpu = 4;
   */
  vCpu: number;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation costCalculation = 5;
   */
  costCalculation?: CostCalculation;
};

/**
 * Describes the message blueapi.api.cover.ResourceDetails.
 * Use `create(ResourceDetailsSchema)` to create a new message.
 */
export declare const ResourceDetailsSchema: GenMessage<ResourceDetails>;

/**
 * @generated from message blueapi.api.cover.UsageTypes
 */
export declare type UsageTypes = Message<"blueapi.api.cover.UsageTypes"> & {
  /**
   * @generated from field: string operation = 1;
   */
  operation: string;

  /**
   * @generated from field: string productCode = 2;
   */
  productCode: string;

  /**
   * @generated from field: string unit = 3;
   */
  unit: string;

  /**
   * @generated from field: double usageAmount = 4;
   */
  usageAmount: number;

  /**
   * @generated from field: string usageType = 5;
   */
  usageType: string;
};

/**
 * Describes the message blueapi.api.cover.UsageTypes.
 * Use `create(UsageTypesSchema)` to create a new message.
 */
export declare const UsageTypesSchema: GenMessage<UsageTypes>;

/**
 * @generated from message blueapi.api.cover.CostCalculation
 */
export declare type CostCalculation = Message<"blueapi.api.cover.CostCalculation"> & {
  /**
   * @generated from field: double estCostAfterDiscount = 1;
   */
  estCostAfterDiscount: number;

  /**
   * @generated from field: double estCostBeforeDiscount = 2;
   */
  estCostBeforeDiscount: number;

  /**
   * @generated from field: double otherDiscount = 3;
   */
  otherDiscount: number;

  /**
   * @generated from field: double savingsPlanDiscount = 4;
   */
  savingsPlanDiscount: number;

  /**
   * @generated from field: double estNetUnusedAmortizedCommitments = 5;
   */
  estNetUnusedAmortizedCommitments: number;

  /**
   * @generated from field: double reservedInstanceDiscount = 7;
   */
  reservedInstanceDiscount: number;

  /**
   * @generated from field: repeated blueapi.api.cover.UsageTypes usageTypes = 6;
   */
  usageTypes: UsageTypes[];
};

/**
 * Describes the message blueapi.api.cover.CostCalculation.
 * Use `create(CostCalculationSchema)` to create a new message.
 */
export declare const CostCalculationSchema: GenMessage<CostCalculation>;

/**
 * @generated from message blueapi.api.cover.UpgradeRecommendationDetails
 */
export declare type UpgradeRecommendationDetails = Message<"blueapi.api.cover.UpgradeRecommendationDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.UpgradeEC2Details upgradeEC2Details = 1;
   */
  upgradeEC2Details?: UpgradeEC2Details;

  /**
   * @generated from field: blueapi.api.cover.EBSDetails upgradeEBSDetails = 2;
   */
  upgradeEBSDetails?: EBSDetails;

  /**
   * @generated from field: blueapi.api.cover.RDSUpgradeDetails upgradeRDSDetails = 5;
   */
  upgradeRDSDetails?: RDSUpgradeDetails;

  /**
   * @generated from field: double estimatedMonthlyCost = 3;
   */
  estimatedMonthlyCost: number;

  /**
   * @generated from field: double estimatedMonthlySavings = 4;
   */
  estimatedMonthlySavings: number;
};

/**
 * Describes the message blueapi.api.cover.UpgradeRecommendationDetails.
 * Use `create(UpgradeRecommendationDetailsSchema)` to create a new message.
 */
export declare const UpgradeRecommendationDetailsSchema: GenMessage<UpgradeRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.UpgradeEC2Details
 */
export declare type UpgradeEC2Details = Message<"blueapi.api.cover.UpgradeEC2Details"> & {
  /**
   * @generated from field: blueapi.api.cover.EC2UpgadeDetails eC2CurrentDetails = 1;
   */
  eC2CurrentDetails?: EC2UpgadeDetails;

  /**
   * @generated from field: blueapi.api.cover.EC2UpgadeDetails ugradeEC2RecommendationDetails = 2;
   */
  ugradeEC2RecommendationDetails?: EC2UpgadeDetails;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation currentCostCalculation = 3;
   */
  currentCostCalculation?: CostCalculation;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation estimatedCostCalculation = 4;
   */
  estimatedCostCalculation?: CostCalculation;
};

/**
 * Describes the message blueapi.api.cover.UpgradeEC2Details.
 * Use `create(UpgradeEC2DetailsSchema)` to create a new message.
 */
export declare const UpgradeEC2DetailsSchema: GenMessage<UpgradeEC2Details>;

/**
 * @generated from message blueapi.api.cover.EC2UpgadeDetails
 */
export declare type EC2UpgadeDetails = Message<"blueapi.api.cover.EC2UpgadeDetails"> & {
  /**
   * @generated from field: string instanceType = 1;
   */
  instanceType: string;

  /**
   * @generated from field: string operation = 2;
   */
  operation: string;

  /**
   * @generated from field: string productCode = 3;
   */
  productCode: string;

  /**
   * @generated from field: string unit = 4;
   */
  unit: string;

  /**
   * @generated from field: double usageAmount = 5;
   */
  usageAmount: number;

  /**
   * @generated from field: string usageType = 6;
   */
  usageType: string;
};

/**
 * Describes the message blueapi.api.cover.EC2UpgadeDetails.
 * Use `create(EC2UpgadeDetailsSchema)` to create a new message.
 */
export declare const EC2UpgadeDetailsSchema: GenMessage<EC2UpgadeDetails>;

/**
 * @generated from message blueapi.api.cover.EBSDetails
 */
export declare type EBSDetails = Message<"blueapi.api.cover.EBSDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.CurrentEBSDetails currentEBSDetails = 1;
   */
  currentEBSDetails?: CurrentEBSDetails;

  /**
   * @generated from field: blueapi.api.cover.EBSRecommendationDetails upgradeEBSDetails = 2;
   */
  upgradeEBSDetails?: EBSRecommendationDetails;
};

/**
 * Describes the message blueapi.api.cover.EBSDetails.
 * Use `create(EBSDetailsSchema)` to create a new message.
 */
export declare const EBSDetailsSchema: GenMessage<EBSDetails>;

/**
 * @generated from message blueapi.api.cover.EBSRecommendationDetails
 */
export declare type EBSRecommendationDetails = Message<"blueapi.api.cover.EBSRecommendationDetails"> & {
  /**
   * @generated from field: string attachmentState = 1;
   */
  attachmentState: string;

  /**
   * @generated from field: double iops = 2;
   */
  iops: number;

  /**
   * @generated from field: double throughput = 3;
   */
  throughput: number;

  /**
   * @generated from field: double sizeInGb = 4;
   */
  sizeInGb: number;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation EstcostCalculation = 5;
   */
  EstcostCalculation?: CostCalculation;
};

/**
 * Describes the message blueapi.api.cover.EBSRecommendationDetails.
 * Use `create(EBSRecommendationDetailsSchema)` to create a new message.
 */
export declare const EBSRecommendationDetailsSchema: GenMessage<EBSRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.CurrentEBSDetails
 */
export declare type CurrentEBSDetails = Message<"blueapi.api.cover.CurrentEBSDetails"> & {
  /**
   * @generated from field: string attachmentState = 1;
   */
  attachmentState: string;

  /**
   * @generated from field: double iops = 2;
   */
  iops: number;

  /**
   * @generated from field: double throughput = 3;
   */
  throughput: number;

  /**
   * @generated from field: double sizeInGb = 4;
   */
  sizeInGb: number;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation costCalculation = 5;
   */
  costCalculation?: CostCalculation;
};

/**
 * Describes the message blueapi.api.cover.CurrentEBSDetails.
 * Use `create(CurrentEBSDetailsSchema)` to create a new message.
 */
export declare const CurrentEBSDetailsSchema: GenMessage<CurrentEBSDetails>;

/**
 * @generated from message blueapi.api.cover.MigrateRecommendationDetails
 */
export declare type MigrateRecommendationDetails = Message<"blueapi.api.cover.MigrateRecommendationDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.MigrateEC2Details migrateEC2Details = 1;
   */
  migrateEC2Details?: MigrateEC2Details;

  /**
   * @generated from field: blueapi.api.cover.MigrateRDSDetails migrateRDSDetails = 4;
   */
  migrateRDSDetails?: MigrateRDSDetails;

  /**
   * @generated from field: double estimatedMonthlyCost = 2;
   */
  estimatedMonthlyCost: number;

  /**
   * @generated from field: double estimatedMonthlySavings = 3;
   */
  estimatedMonthlySavings: number;
};

/**
 * Describes the message blueapi.api.cover.MigrateRecommendationDetails.
 * Use `create(MigrateRecommendationDetailsSchema)` to create a new message.
 */
export declare const MigrateRecommendationDetailsSchema: GenMessage<MigrateRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.MigrateEC2Details
 */
export declare type MigrateEC2Details = Message<"blueapi.api.cover.MigrateEC2Details"> & {
  /**
   * @generated from field: blueapi.api.cover.EC2UpgadeDetails eC2CurrentDetails = 1;
   */
  eC2CurrentDetails?: EC2UpgadeDetails;

  /**
   * @generated from field: blueapi.api.cover.EC2UpgadeDetails ugradeEC2RecommendationDetails = 2;
   */
  ugradeEC2RecommendationDetails?: EC2UpgadeDetails;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation currentCostCalculation = 3;
   */
  currentCostCalculation?: CostCalculation;

  /**
   * @generated from field: blueapi.api.cover.CostCalculation estCostCalculation = 4;
   */
  estCostCalculation?: CostCalculation;
};

/**
 * Describes the message blueapi.api.cover.MigrateEC2Details.
 * Use `create(MigrateEC2DetailsSchema)` to create a new message.
 */
export declare const MigrateEC2DetailsSchema: GenMessage<MigrateEC2Details>;

/**
 * @generated from message blueapi.api.cover.StopInstanceRecommendationDetails
 */
export declare type StopInstanceRecommendationDetails = Message<"blueapi.api.cover.StopInstanceRecommendationDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.StopEC2InstanceRecommendationDetails stopEC2InstanceRecommendationDetails = 1;
   */
  stopEC2InstanceRecommendationDetails?: StopEC2InstanceRecommendationDetails;

  /**
   * @generated from field: blueapi.api.cover.StopRDSDetails stopRDSRecommendationDetails = 2;
   */
  stopRDSRecommendationDetails?: StopRDSDetails;
};

/**
 * Describes the message blueapi.api.cover.StopInstanceRecommendationDetails.
 * Use `create(StopInstanceRecommendationDetailsSchema)` to create a new message.
 */
export declare const StopInstanceRecommendationDetailsSchema: GenMessage<StopInstanceRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.DeleteRecommendationDetails
 */
export declare type DeleteRecommendationDetails = Message<"blueapi.api.cover.DeleteRecommendationDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.CurrentEC2Details ec2Details = 1;
   */
  ec2Details?: CurrentEC2Details;

  /**
   * @generated from field: blueapi.api.cover.EbsVolumeDetails ebsVolumeDetails = 2;
   */
  ebsVolumeDetails?: EbsVolumeDetails;

  /**
   * @generated from field: blueapi.api.cover.ElasticIpAddressDetails elasticIpAddressDetails = 3;
   */
  elasticIpAddressDetails?: ElasticIpAddressDetails;

  /**
   * @generated from field: blueapi.api.cover.IdleRdsDetails idleRdsDetails = 4;
   */
  idleRdsDetails?: IdleRdsDetails;

  /**
   * @generated from field: blueapi.api.cover.IdleLoadBalancerDetails idleLoadBalancerDetails = 5;
   */
  idleLoadBalancerDetails?: IdleLoadBalancerDetails;

  /**
   * @generated from field: string exclusionStatus = 6;
   */
  exclusionStatus: string;

  /**
   * @generated from field: string status = 7;
   */
  status: string;
};

/**
 * Describes the message blueapi.api.cover.DeleteRecommendationDetails.
 * Use `create(DeleteRecommendationDetailsSchema)` to create a new message.
 */
export declare const DeleteRecommendationDetailsSchema: GenMessage<DeleteRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.EbsVolumeDetails
 */
export declare type EbsVolumeDetails = Message<"blueapi.api.cover.EbsVolumeDetails"> & {
  /**
   * @generated from field: string volumeId = 1;
   */
  volumeId: string;

  /**
   * @generated from field: int64 volumeSize = 2;
   */
  volumeSize: bigint;

  /**
   * @generated from field: string volumeType = 3;
   */
  volumeType: string;

  /**
   * @generated from field: double monthlyStorageCost = 4;
   */
  monthlyStorageCost: number;
};

/**
 * Describes the message blueapi.api.cover.EbsVolumeDetails.
 * Use `create(EbsVolumeDetailsSchema)` to create a new message.
 */
export declare const EbsVolumeDetailsSchema: GenMessage<EbsVolumeDetails>;

/**
 * @generated from message blueapi.api.cover.ElasticIpAddressDetails
 */
export declare type ElasticIpAddressDetails = Message<"blueapi.api.cover.ElasticIpAddressDetails"> & {
  /**
   * @generated from field: string ipAddress = 2;
   */
  ipAddress: string;

  /**
   * @generated from field: string service = 3;
   */
  service: string;
};

/**
 * Describes the message blueapi.api.cover.ElasticIpAddressDetails.
 * Use `create(ElasticIpAddressDetailsSchema)` to create a new message.
 */
export declare const ElasticIpAddressDetailsSchema: GenMessage<ElasticIpAddressDetails>;

/**
 * @generated from message blueapi.api.cover.IdleRdsDetails
 */
export declare type IdleRdsDetails = Message<"blueapi.api.cover.IdleRdsDetails"> & {
  /**
   * @generated from field: string dbInstanceName = 1;
   */
  dbInstanceName: string;

  /**
   * @generated from field: string daysSinceLastConnection = 2;
   */
  daysSinceLastConnection: string;

  /**
   * @generated from field: string instanceType = 3;
   */
  instanceType: string;

  /**
   * @generated from field: string multiAZ = 4;
   */
  multiAZ: string;

  /**
   * @generated from field: double storageProvisioned = 5;
   */
  storageProvisioned: number;
};

/**
 * Describes the message blueapi.api.cover.IdleRdsDetails.
 * Use `create(IdleRdsDetailsSchema)` to create a new message.
 */
export declare const IdleRdsDetailsSchema: GenMessage<IdleRdsDetails>;

/**
 * @generated from message blueapi.api.cover.IdleLoadBalancerDetails
 */
export declare type IdleLoadBalancerDetails = Message<"blueapi.api.cover.IdleLoadBalancerDetails"> & {
  /**
   * @generated from field: string loadBalancerName = 1;
   */
  loadBalancerName: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * @generated from field: string service = 3;
   */
  service: string;
};

/**
 * Describes the message blueapi.api.cover.IdleLoadBalancerDetails.
 * Use `create(IdleLoadBalancerDetailsSchema)` to create a new message.
 */
export declare const IdleLoadBalancerDetailsSchema: GenMessage<IdleLoadBalancerDetails>;

/**
 * @generated from message blueapi.api.cover.OtherRecommendationDetails
 */
export declare type OtherRecommendationDetails = Message<"blueapi.api.cover.OtherRecommendationDetails"> & {
  /**
   * @generated from field: blueapi.api.cover.HighErrorRatesLambda highErrorRatesLambda = 1;
   */
  highErrorRatesLambda?: HighErrorRatesLambda;

  /**
   * @generated from field: blueapi.api.cover.S3IncompleteMultiPartUploadAbortConfiguration s3IncompleteMultiPartUploadAbortConfiguration = 2;
   */
  s3IncompleteMultiPartUploadAbortConfiguration?: S3IncompleteMultiPartUploadAbortConfiguration;

  /**
   * @generated from field: string status = 3;
   */
  status: string;
};

/**
 * Describes the message blueapi.api.cover.OtherRecommendationDetails.
 * Use `create(OtherRecommendationDetailsSchema)` to create a new message.
 */
export declare const OtherRecommendationDetailsSchema: GenMessage<OtherRecommendationDetails>;

/**
 * @generated from message blueapi.api.cover.HighErrorRatesLambda
 */
export declare type HighErrorRatesLambda = Message<"blueapi.api.cover.HighErrorRatesLambda"> & {
  /**
   * @generated from field: double avgDailyErrorRates = 1;
   */
  avgDailyErrorRates: number;

  /**
   * @generated from field: double avgDailyInvokes = 2;
   */
  avgDailyInvokes: number;

  /**
   * @generated from field: double currentDayErrorRates = 3;
   */
  currentDayErrorRates: number;

  /**
   * @generated from field: double currentDayInvokes = 4;
   */
  currentDayInvokes: number;

  /**
   * @generated from field: string dateForMaxErrorRates = 5;
   */
  dateForMaxErrorRates: string;

  /**
   * @generated from field: string functionArn = 6;
   */
  functionArn: string;

  /**
   * @generated from field: double lostDailyComputeCost = 7;
   */
  lostDailyComputeCost: number;

  /**
   * @generated from field: double maxDailyErrorRates = 8;
   */
  maxDailyErrorRates: number;
};

/**
 * Describes the message blueapi.api.cover.HighErrorRatesLambda.
 * Use `create(HighErrorRatesLambdaSchema)` to create a new message.
 */
export declare const HighErrorRatesLambdaSchema: GenMessage<HighErrorRatesLambda>;

/**
 * @generated from message blueapi.api.cover.S3IncompleteMultiPartUploadAbortConfiguration
 */
export declare type S3IncompleteMultiPartUploadAbortConfiguration = Message<"blueapi.api.cover.S3IncompleteMultiPartUploadAbortConfiguration"> & {
  /**
   * @generated from field: string bucketArn = 1;
   */
  bucketArn: string;

  /**
   * @generated from field: string bucketName = 2;
   */
  bucketName: string;

  /**
   * @generated from field: string lifeCycleRuleForDeletingIncompleteMCU = 3;
   */
  lifeCycleRuleForDeletingIncompleteMCU: string;

  /**
   * @generated from field: string daysAfterInitiation = 4;
   */
  daysAfterInitiation: string;
};

/**
 * Describes the message blueapi.api.cover.S3IncompleteMultiPartUploadAbortConfiguration.
 * Use `create(S3IncompleteMultiPartUploadAbortConfigurationSchema)` to create a new message.
 */
export declare const S3IncompleteMultiPartUploadAbortConfigurationSchema: GenMessage<S3IncompleteMultiPartUploadAbortConfiguration>;

/**
 * @generated from message blueapi.api.cover.StopEC2InstanceRecommendationDetails
 */
export declare type StopEC2InstanceRecommendationDetails = Message<"blueapi.api.cover.StopEC2InstanceRecommendationDetails"> & {
  /**
   * @generated from field: string instanceId = 1;
   */
  instanceId: string;

  /**
   * @generated from field: string instanceType = 2;
   */
  instanceType: string;

  /**
   * @generated from field: double AveCpuUtilizationBy14Day = 3;
   */
  AveCpuUtilizationBy14Day: number;

  /**
   * @generated from field: double AveNetworkIOBy14Day = 4;
   */
  AveNetworkIOBy14Day: number;

  /**
   * @generated from field: repeated blueapi.api.cover.UtilizationData cpuUtilization = 5;
   */
  cpuUtilization: UtilizationData[];

  /**
   * @generated from field: repeated blueapi.api.cover.UtilizationData netWorkIO = 6;
   */
  netWorkIO: UtilizationData[];
};

/**
 * Describes the message blueapi.api.cover.StopEC2InstanceRecommendationDetails.
 * Use `create(StopEC2InstanceRecommendationDetailsSchema)` to create a new message.
 */
export declare const StopEC2InstanceRecommendationDetailsSchema: GenMessage<StopEC2InstanceRecommendationDetails>;

