// @generated by protoc-gen-es v2.7.0
// @generated from file vortex/v1/vortex.proto (package blueapi.vortex.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_protoc_gen_openapiv2_options_annotations } from "../../protoc-gen-openapiv2/options/annotations_pb";

/**
 * Describes the file vortex/v1/vortex.proto.
 */
export const file_vortex_v1_vortex = /*@__PURE__*/
  fileDesc("ChZ2b3J0ZXgvdjEvdm9ydGV4LnByb3RvEhFibHVlYXBpLnZvcnRleC52MSIfCgxUZXN0UmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCSIvChBDcmVhdGVPcmdSZXF1ZXN0EgwKBG5hbWUYASABKAkSDQoFZW1haWwYAiABKAkiPwoRQ3JlYXRlT3JnUmVzcG9uc2USDQoFb3JnSWQYASABKAkSDAoEbmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCSIfCg5HZXRVc2VyUmVxdWVzdBINCgVlbWFpbBgBIAEoCSJJCg9HZXRVc2VyUmVzcG9uc2USCgoCaWQYASABKAkSDQoFZW1haWwYAiABKAkSDAoEbmFtZRgDIAEoCRINCgVvcmdJZBgEIAEoCSJHCgZQcm9tcHQSDwoHY29udGVudBgBIAEoCRIZChFmcm9tQ29udGFpbmVyTmFtZRgCIAEoCRIRCglyaXNrTGV2ZWwYAyABKAkiFAoSTGlzdFByb21wdHNSZXF1ZXN0IiIKEUludml0ZVVzZXJSZXF1ZXN0Eg0KBWVtYWlsGAEgASgJIkYKGFZlcmlmeUludml0ZWRVc2VyUmVxdWVzdBINCgVlbWFpbBgBIAEoCRINCgVvcmdJZBgCIAEoCRIMCgRjb2RlGAMgASgJMqkGCgZWb3J0ZXgSVAoEVGVzdBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRofLmJsdWVhcGkudm9ydGV4LnYxLlRlc3RSZXNwb25zZSITgtPkkwINEgsvdjEvdGVzdGluZxJ0CglDcmVhdGVPcmcSIy5ibHVlYXBpLnZvcnRleC52MS5DcmVhdGVPcmdSZXF1ZXN0GiQuYmx1ZWFwaS52b3J0ZXgudjEuQ3JlYXRlT3JnUmVzcG9uc2UiHILT5JMCFjoBKiIRL3YxL29yZ2FuaXphdGlvbnMSagoHR2V0VXNlchIhLmJsdWVhcGkudm9ydGV4LnYxLkdldFVzZXJSZXF1ZXN0GiIuYmx1ZWFwaS52b3J0ZXgudjEuR2V0VXNlclJlc3BvbnNlIhiC0+STAhISEC92MS91c2VyL3tlbWFpbH0SbgoLTGlzdFByb21wdHMSJS5ibHVlYXBpLnZvcnRleC52MS5MaXN0UHJvbXB0c1JlcXVlc3QaGS5ibHVlYXBpLnZvcnRleC52MS5Qcm9tcHQiG4LT5JMCFToBKiIQL3YxL3Byb21wdHM6cmVhZDABEmEKCkludml0ZVVzZXISJC5ibHVlYXBpLnZvcnRleC52MS5JbnZpdGVVc2VyUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIVgtPkkwIPOgEqIgovdjEvaW52aXRlEnYKEVZlcmlmeUludml0ZWRVc2VyEisuYmx1ZWFwaS52b3J0ZXgudjEuVmVyaWZ5SW52aXRlZFVzZXJSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IhyC0+STAhY6ASoiES92MS9pbnZpdGUvdmVyaWZ5GpsBkkGXARJFKEFscGhhKSBWb3J0ZXggQVBJLiBCYXNlIFVSTDogaHR0cHM6Ly9hcGkuYWxwaGF1cy5jbG91ZC9tL2JsdWUvdm9ydGV4Gk4KElNlcnZpY2UgZGVmaW5pdGlvbhI4aHR0cHM6Ly9naXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWVhcGkvdHJlZS9tYWluL3ZvcnRleC9CTgoYY2xvdWQuYWxwaGF1cy5hcGkudm9ydGV4QgtWb3J0ZXhQcm90b1olZ2l0aHViLmNvbS9hbHBoYXVzbGFicy9ibHVlYXBpL3ZvcnRleGIGcHJvdG8z", [file_google_protobuf_empty, file_google_api_annotations, file_protoc_gen_openapiv2_options_annotations]);

/**
 * Describes the message blueapi.vortex.v1.TestResponse.
 * Use `create(TestResponseSchema)` to create a new message.
 */
export const TestResponseSchema = /*@__PURE__*/
  messageDesc(file_vortex_v1_vortex, 0);

/**
 * Describes the message blueapi.vortex.v1.CreateOrgRequest.
 * Use `create(CreateOrgRequestSchema)` to create a new message.
 */
export const CreateOrgRequestSchema = /*@__PURE__*/
  messageDesc(file_vortex_v1_vortex, 1);

/**
 * Describes the message blueapi.vortex.v1.CreateOrgResponse.
 * Use `create(CreateOrgResponseSchema)` to create a new message.
 */
export const CreateOrgResponseSchema = /*@__PURE__*/
  messageDesc(file_vortex_v1_vortex, 2);

/**
 * Describes the message blueapi.vortex.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema = /*@__PURE__*/
  messageDesc(file_vortex_v1_vortex, 3);

/**
 * Describes the message blueapi.vortex.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema = /*@__PURE__*/
  messageDesc(file_vortex_v1_vortex, 4);

/**
 * Describes the message blueapi.vortex.v1.Prompt.
 * Use `create(PromptSchema)` to create a new message.
 */
export const PromptSchema = /*@__PURE__*/
  messageDesc(file_vortex_v1_vortex, 5);

/**
 * Describes the message blueapi.vortex.v1.ListPromptsRequest.
 * Use `create(ListPromptsRequestSchema)` to create a new message.
 */
export const ListPromptsRequestSchema = /*@__PURE__*/
  messageDesc(file_vortex_v1_vortex, 6);

/**
 * Describes the message blueapi.vortex.v1.InviteUserRequest.
 * Use `create(InviteUserRequestSchema)` to create a new message.
 */
export const InviteUserRequestSchema = /*@__PURE__*/
  messageDesc(file_vortex_v1_vortex, 7);

/**
 * Describes the message blueapi.vortex.v1.VerifyInvitedUserRequest.
 * Use `create(VerifyInvitedUserRequestSchema)` to create a new message.
 */
export const VerifyInvitedUserRequestSchema = /*@__PURE__*/
  messageDesc(file_vortex_v1_vortex, 8);

/**
 * Vortex service definition.
 *
 * @generated from service blueapi.vortex.v1.Vortex
 */
export const Vortex = /*@__PURE__*/
  serviceDesc(file_vortex_v1_vortex, 0);

