// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file flags/v1/flags.proto (package blueapi.flags.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_protoc_gen_openapiv2_options_annotations } from "../../protoc-gen-openapiv2/options/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file flags/v1/flags.proto.
 */
export const file_flags_v1_flags: GenFile = /*@__PURE__*/
  fileDesc("ChRmbGFncy92MS9mbGFncy5wcm90bxIQYmx1ZWFwaS5mbGFncy52MSLNAQoaRXZhbHVhdGVCb29sZWFuRmxhZ1JlcXVlc3QSFAoMbmFtZXNwYWNlX2lkGAEgASgJEgoKAmlkGAIgASgJEhQKB3NlZ21lbnQYAyABKAlIAIgBARJACgJrdhgEIAMoCzI0LmJsdWVhcGkuZmxhZ3MudjEuRXZhbHVhdGVCb29sZWFuRmxhZ1JlcXVlc3QuS3ZFbnRyeRopCgdLdkVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFCCgoIX3NlZ21lbnQiLAobRXZhbHVhdGVCb29sZWFuRmxhZ1Jlc3BvbnNlEg0KBXZhbHVlGAEgASgIIqsBChpFdmFsdWF0ZVZhcmlhbnRGbGFnUmVxdWVzdBIUCgxuYW1lc3BhY2VfaWQYASABKAkSCgoCaWQYAiABKAkSQAoCa3YYAyADKAsyNC5ibHVlYXBpLmZsYWdzLnYxLkV2YWx1YXRlVmFyaWFudEZsYWdSZXF1ZXN0Lkt2RW50cnkaKQoHS3ZFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIrIBChtFdmFsdWF0ZVZhcmlhbnRGbGFnUmVzcG9uc2USDQoFdmFsdWUYASABKAkSUQoKYXR0YWNobWVudBgCIAMoCzI9LmJsdWVhcGkuZmxhZ3MudjEuRXZhbHVhdGVWYXJpYW50RmxhZ1Jlc3BvbnNlLkF0dGFjaG1lbnRFbnRyeRoxCg9BdHRhY2htZW50RW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ATKGBAoFRmxhZ3MSswEKE0V2YWx1YXRlQm9vbGVhbkZsYWcSLC5ibHVlYXBpLmZsYWdzLnYxLkV2YWx1YXRlQm9vbGVhbkZsYWdSZXF1ZXN0Gi0uYmx1ZWFwaS5mbGFncy52MS5FdmFsdWF0ZUJvb2xlYW5GbGFnUmVzcG9uc2UiP4LT5JMCOToBKiI0L2ZsYWdzL3YxL25hbWVzcGFjZS97bmFtZXNwYWNlX2lkfS9ib29sZWFuL3tpZH06ZXZhbBKzAQoTRXZhbHVhdGVWYXJpYW50RmxhZxIsLmJsdWVhcGkuZmxhZ3MudjEuRXZhbHVhdGVWYXJpYW50RmxhZ1JlcXVlc3QaLS5ibHVlYXBpLmZsYWdzLnYxLkV2YWx1YXRlVmFyaWFudEZsYWdSZXNwb25zZSI/gtPkkwI5OgEqIjQvZmxhZ3MvdjEvbmFtZXNwYWNlL3tuYW1lc3BhY2VfaWR9L3ZhcmlhbnQve2lkfTpldmFsGpABkkGMARI8KEFMUEhBKSBGbGFnIEFQSS4gQmFzZSBVUkw6IGh0dHBzOi8vYXBpLmFscGhhdXMuY2xvdWQvbS9ibHVlGkwKElNlcnZpY2UgZGVmaW5pdGlvbhI2aHR0cHM6Ly9naXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWVhcGkvdHJlZS9tYWluL2ZsYWdzQksKF2Nsb3VkLmFscGhhdXMuYXBpLmZsYWdzQgpGbGFnc1Byb3RvWiRnaXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWVhcGkvZmxhZ3NiBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_empty, file_protoc_gen_openapiv2_options_annotations]);

/**
 * @generated from message blueapi.flags.v1.EvaluateBooleanFlagRequest
 */
export type EvaluateBooleanFlagRequest = Message<"blueapi.flags.v1.EvaluateBooleanFlagRequest"> & {
  /**
   * Required. The namespaceId that the flag belongs to.
   *
   * @generated from field: string namespace_id = 1;
   */
  namespaceId: string;

  /**
   * Required. The flagId
   *
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * Optional. The segment to evaluate the flag for. If not provided, the default value of the flag will be returned.
   *
   * @generated from field: optional string segment = 3;
   */
  segment?: string;

  /**
   * Optional. Key-value pairs for additional context when evaluating the flag. Must be provided if segment is present.
   *
   * @generated from field: map<string, string> kv = 4;
   */
  kv: { [key: string]: string };
};

/**
 * Describes the message blueapi.flags.v1.EvaluateBooleanFlagRequest.
 * Use `create(EvaluateBooleanFlagRequestSchema)` to create a new message.
 */
export const EvaluateBooleanFlagRequestSchema: GenMessage<EvaluateBooleanFlagRequest> = /*@__PURE__*/
  messageDesc(file_flags_v1_flags, 0);

/**
 * @generated from message blueapi.flags.v1.EvaluateBooleanFlagResponse
 */
export type EvaluateBooleanFlagResponse = Message<"blueapi.flags.v1.EvaluateBooleanFlagResponse"> & {
  /**
   * The boolean value of the flag.
   *
   * @generated from field: bool value = 1;
   */
  value: boolean;
};

/**
 * Describes the message blueapi.flags.v1.EvaluateBooleanFlagResponse.
 * Use `create(EvaluateBooleanFlagResponseSchema)` to create a new message.
 */
export const EvaluateBooleanFlagResponseSchema: GenMessage<EvaluateBooleanFlagResponse> = /*@__PURE__*/
  messageDesc(file_flags_v1_flags, 1);

/**
 * @generated from message blueapi.flags.v1.EvaluateVariantFlagRequest
 */
export type EvaluateVariantFlagRequest = Message<"blueapi.flags.v1.EvaluateVariantFlagRequest"> & {
  /**
   * Required. The namespaceId that the flag belongs to.
   *
   * @generated from field: string namespace_id = 1;
   */
  namespaceId: string;

  /**
   * Required. The flagId
   *
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * Optional. Key-value pairs for additional context when evaluating the flag. 
   *
   * @generated from field: map<string, string> kv = 3;
   */
  kv: { [key: string]: string };
};

/**
 * Describes the message blueapi.flags.v1.EvaluateVariantFlagRequest.
 * Use `create(EvaluateVariantFlagRequestSchema)` to create a new message.
 */
export const EvaluateVariantFlagRequestSchema: GenMessage<EvaluateVariantFlagRequest> = /*@__PURE__*/
  messageDesc(file_flags_v1_flags, 2);

/**
 * @generated from message blueapi.flags.v1.EvaluateVariantFlagResponse
 */
export type EvaluateVariantFlagResponse = Message<"blueapi.flags.v1.EvaluateVariantFlagResponse"> & {
  /**
   * The variant value of the flag. Empty string if no match is found.
   *
   * @generated from field: string value = 1;
   */
  value: string;

  /**
   * Optional. The attachment attached to the returned variant.
   *
   * @generated from field: map<string, string> attachment = 2;
   */
  attachment: { [key: string]: string };
};

/**
 * Describes the message blueapi.flags.v1.EvaluateVariantFlagResponse.
 * Use `create(EvaluateVariantFlagResponseSchema)` to create a new message.
 */
export const EvaluateVariantFlagResponseSchema: GenMessage<EvaluateVariantFlagResponse> = /*@__PURE__*/
  messageDesc(file_flags_v1_flags, 3);

/**
 * Flags service definition.
 *
 * @generated from service blueapi.flags.v1.Flags
 */
export const Flags: GenService<{
  /**
   * EvaluateBooleanFlag returns the boolean value of a flag for a given namespace.
   *
   * @generated from rpc blueapi.flags.v1.Flags.EvaluateBooleanFlag
   */
  evaluateBooleanFlag: {
    methodKind: "unary";
    input: typeof EvaluateBooleanFlagRequestSchema;
    output: typeof EvaluateBooleanFlagResponseSchema;
  },
  /**
   * EvaluateVariantFlag returns the variant value of a flag for a given namespace.
   *
   * @generated from rpc blueapi.flags.v1.Flags.EvaluateVariantFlag
   */
  evaluateVariantFlag: {
    methodKind: "unary";
    input: typeof EvaluateVariantFlagRequestSchema;
    output: typeof EvaluateVariantFlagResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_flags_v1_flags, 0);

