"use strict";
// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file api/azure/cost.proto (package blueapi.api.azure, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CostAttributeSchema = exports.CostSchema = exports.file_api_azure_cost = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
/**
 * Describes the file api/azure/cost.proto.
 */
exports.file_api_azure_cost = (0, codegenv2_1.fileDesc)("ChRhcGkvYXp1cmUvY29zdC5wcm90bxIRYmx1ZWFwaS5hcGkuYXp1cmUihgQKBENvc3QSDwoHYWNjb3VudBgBIAEoCRIPCgdncm91cElkGAIgASgJEgwKBGRhdGUYAyABKAkSEwoLc2VydmljZU5hbWUYBCABKAkSEwoLcHJvZHVjdE5hbWUYBSABKAkSDgoGcmVnaW9uGAYgASgJEhIKCmNoYXJnZVR5cGUYByABKAkSEwoLZGVzY3JpcHRpb24YCCABKAkSGAoQYmlsbGFibGVRdWFudGl0eRgJIAEoARIaChJlZmZlY3RpdmVVbml0UHJpY2UYCiABKAESDAoEY29zdBgLIAEoARIUCgxiYXNlQ3VycmVuY3kYDCABKAkSFAoMZXhjaGFuZ2VSYXRlGA0gASgBEhIKCnRhcmdldENvc3QYDiABKAESFgoOdGFyZ2V0Q3VycmVuY3kYDyABKAkSFAoMdGltZUludGVydmFsGBAgASgJEhMKC2JpbGxpbmdUeXBlGBEgASgJEhMKC2FsdGVybmF0ZUlkGBIgASgJEhIKCmRvbWFpbk5hbWUYEyABKAkSEQoJb3BlcmF0aW9uGBQgASgJEhEKCXVzYWdlVHlwZRgVIAEoCRIUCgxpbnN0YW5jZVR5cGUYFiABKAkSEAoIY2F0ZWdvcnkYFyABKAkSFgoOc3Vic2NyaXB0aW9uSWQYGCABKAkSFQoNZW50aXRsZW1lbnRJZBgZIAEoCSLmAQoNQ29zdEF0dHJpYnV0ZRISCgpjdXN0b21lcklkGAEgASgJEhYKDnN1YnNjcmlwdGlvbklkGAIgASgJEhUKDWVudGl0bGVtZW50SWQYAyABKAkSDwoHZ3JvdXBJZBgEIAEoCRIRCglwcm9kdWN0SWQYBSABKAkSEwoLcHJvZHVjdE5hbWUYBiABKAkSDQoFc2t1SWQYByABKAkSDwoHc2t1TmFtZRgIIAEoCRITCgtkZXNjcmlwdGlvbhgJIAEoCRIQCghjYXRlZ29yeRgKIAEoCRISCgpkb21haW5OYW1lGAsgASgJQmIKH2Nsb3VkLmFscGhhdXMuYmx1ZWFwaS5hcGkuYXp1cmVCEUFwaUF6dXJlQ29zdFByb3RvWixnaXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWUtc2RrLWdvL2FwaS9henVyZWIGcHJvdG8z");
/**
 * Describes the message blueapi.api.azure.Cost.
 * Use `create(CostSchema)` to create a new message.
 */
exports.CostSchema = (0, codegenv2_1.messageDesc)(exports.file_api_azure_cost, 0);
/**
 * Describes the message blueapi.api.azure.CostAttribute.
 * Use `create(CostAttributeSchema)` to create a new message.
 */
exports.CostAttributeSchema = (0, codegenv2_1.messageDesc)(exports.file_api_azure_cost, 1);
