// @generated by protoc-gen-es v2.7.0
// @generated from file api/adjustment.proto (package blueapi.api, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file api/adjustment.proto.
 */
export const file_api_adjustment = /*@__PURE__*/
  fileDesc("ChRhcGkvYWRqdXN0bWVudC5wcm90bxILYmx1ZWFwaS5hcGkigAEKEEFkanVzdG1lbnRDb25maWcSKgoGY29uZmlnGAEgAygLMhouYmx1ZWFwaS5hcGkuQ29uZmlnRmlsdGVycxIOCgZ2ZW5kb3IYAiABKAkSMAoIYWNjb3VudHMYAyADKAsyHi5ibHVlYXBpLmFwaS5NYW5hZ2VtZW50QWNjb3VudCJcChFNYW5hZ2VtZW50QWNjb3VudBIbChNtYW5hZ2VtZW50QWNjb3VudElkGAEgASgJEioKBmNvbmZpZxgCIAMoCzIaLmJsdWVhcGkuYXBpLkNvbmZpZ0ZpbHRlcnMiggEKDUNvbmZpZ0ZpbHRlcnMSPgoKYW5kRmlsdGVycxgBIAMoCzIqLmJsdWVhcGkuYXBpLkNvbmZpZ0ZpbHRlcnMuQW5kRmlsdGVyc0VudHJ5GjEKD0FuZEZpbHRlcnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQlcKGWNsb3VkLmFscGhhdXMuYmx1ZWFwaS5hcGlCEkFwaUFkanVzdG1lbnRQcm90b1omZ2l0aHViLmNvbS9hbHBoYXVzbGFicy9ibHVlLXNkay1nby9hcGliBnByb3RvMw");

/**
 * Describes the message blueapi.api.AdjustmentConfig.
 * Use `create(AdjustmentConfigSchema)` to create a new message.
 */
export const AdjustmentConfigSchema = /*@__PURE__*/
  messageDesc(file_api_adjustment, 0);

/**
 * Describes the message blueapi.api.ManagementAccount.
 * Use `create(ManagementAccountSchema)` to create a new message.
 */
export const ManagementAccountSchema = /*@__PURE__*/
  messageDesc(file_api_adjustment, 1);

/**
 * Describes the message blueapi.api.ConfigFilters.
 * Use `create(ConfigFiltersSchema)` to create a new message.
 */
export const ConfigFiltersSchema = /*@__PURE__*/
  messageDesc(file_api_adjustment, 2);

