"use strict";
// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file api/adjustment.proto (package blueapi.api, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfigFiltersSchema = exports.ManagementAccountSchema = exports.AdjustmentConfigSchema = exports.file_api_adjustment = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
/**
 * Describes the file api/adjustment.proto.
 */
exports.file_api_adjustment = (0, codegenv2_1.fileDesc)("ChRhcGkvYWRqdXN0bWVudC5wcm90bxILYmx1ZWFwaS5hcGkigAEKEEFkanVzdG1lbnRDb25maWcSKgoGY29uZmlnGAEgAygLMhouYmx1ZWFwaS5hcGkuQ29uZmlnRmlsdGVycxIOCgZ2ZW5kb3IYAiABKAkSMAoIYWNjb3VudHMYAyADKAsyHi5ibHVlYXBpLmFwaS5NYW5hZ2VtZW50QWNjb3VudCJcChFNYW5hZ2VtZW50QWNjb3VudBIbChNtYW5hZ2VtZW50QWNjb3VudElkGAEgASgJEioKBmNvbmZpZxgCIAMoCzIaLmJsdWVhcGkuYXBpLkNvbmZpZ0ZpbHRlcnMiggEKDUNvbmZpZ0ZpbHRlcnMSPgoKYW5kRmlsdGVycxgBIAMoCzIqLmJsdWVhcGkuYXBpLkNvbmZpZ0ZpbHRlcnMuQW5kRmlsdGVyc0VudHJ5GjEKD0FuZEZpbHRlcnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQlcKGWNsb3VkLmFscGhhdXMuYmx1ZWFwaS5hcGlCEkFwaUFkanVzdG1lbnRQcm90b1omZ2l0aHViLmNvbS9hbHBoYXVzbGFicy9ibHVlLXNkay1nby9hcGliBnByb3RvMw");
/**
 * Describes the message blueapi.api.AdjustmentConfig.
 * Use `create(AdjustmentConfigSchema)` to create a new message.
 */
exports.AdjustmentConfigSchema = (0, codegenv2_1.messageDesc)(exports.file_api_adjustment, 0);
/**
 * Describes the message blueapi.api.ManagementAccount.
 * Use `create(ManagementAccountSchema)` to create a new message.
 */
exports.ManagementAccountSchema = (0, codegenv2_1.messageDesc)(exports.file_api_adjustment, 1);
/**
 * Describes the message blueapi.api.ConfigFilters.
 * Use `create(ConfigFiltersSchema)` to create a new message.
 */
exports.ConfigFiltersSchema = (0, codegenv2_1.messageDesc)(exports.file_api_adjustment, 2);
