"use strict";
// @generated by protoc-gen-es v2.5.0 with parameter "target=ts"
// @generated from file api/budget.proto (package blueapi.api, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BudgetAlertNotificationDetailSchema = exports.BudgetAlertNotificationSchema = exports.CustomPeriodBudgetAlertSchema = exports.MonthlyBudgetAlertSchema = exports.DailyRateIncreaseBudgetAlertSchema = exports.DailyBudgetAlertSchema = exports.MonthlyBudgetSchema = exports.BudgetSchema = exports.file_api_budget = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
const notification_pb_1 = require("./notification_pb");
/**
 * Describes the file api/budget.proto.
 */
exports.file_api_budget = (0, codegenv2_1.fileDesc)("ChBhcGkvYnVkZ2V0LnByb3RvEgtibHVlYXBpLmFwaSJbCgZCdWRnZXQSCgoCaWQYASABKAkSEgoKZmlzY2FsWWVhchgCIAEoCRIxCg1tb250aGx5QnVkZ2V0GAMgAygLMhouYmx1ZWFwaS5hcGkuTW9udGhseUJ1ZGdldCIyCg1Nb250aGx5QnVkZ2V0EhEKCXllYXJNb250aBgBIAEoCRIOCgZhbW91bnQYAiABKAEiMgoQRGFpbHlCdWRnZXRBbGVydBINCgV2YWx1ZRgBIAEoARIPCgdlbmFibGVkGAIgASgIIj4KHERhaWx5UmF0ZUluY3JlYXNlQnVkZ2V0QWxlcnQSDQoFdmFsdWUYASABKAESDwoHZW5hYmxlZBgCIAEoCCI0ChJNb250aGx5QnVkZ2V0QWxlcnQSDQoFdmFsdWUYASABKAESDwoHZW5hYmxlZBgCIAEoCCJdChdDdXN0b21QZXJpb2RCdWRnZXRBbGVydBINCgV2YWx1ZRgBIAEoARIPCgdlbmFibGVkGAIgASgIEhEKCXN0YXJ0RGF0ZRgDIAEoCRIPCgdlbmREYXRlGAQgASgJIjwKF0J1ZGdldEFsZXJ0Tm90aWZpY2F0aW9uEhAKCGNoYW5uZWxzGAIgAygJEg8KB2VuYWJsZWQYAyABKAgiZAodQnVkZ2V0QWxlcnROb3RpZmljYXRpb25EZXRhaWwSMgoIY2hhbm5lbHMYAiADKAsyIC5ibHVlYXBpLmFwaS5Ob3RpZmljYXRpb25DaGFubmVsEg8KB2VuYWJsZWQYAyABKAhCUwoZY2xvdWQuYWxwaGF1cy5ibHVlYXBpLmFwaUIOQXBpQnVkZ2V0UHJvdG9aJmdpdGh1Yi5jb20vYWxwaGF1c2xhYnMvYmx1ZS1zZGstZ28vYXBpYgZwcm90bzM", [notification_pb_1.file_api_notification]);
/**
 * Describes the message blueapi.api.Budget.
 * Use `create(BudgetSchema)` to create a new message.
 */
exports.BudgetSchema = (0, codegenv2_1.messageDesc)(exports.file_api_budget, 0);
/**
 * Describes the message blueapi.api.MonthlyBudget.
 * Use `create(MonthlyBudgetSchema)` to create a new message.
 */
exports.MonthlyBudgetSchema = (0, codegenv2_1.messageDesc)(exports.file_api_budget, 1);
/**
 * Describes the message blueapi.api.DailyBudgetAlert.
 * Use `create(DailyBudgetAlertSchema)` to create a new message.
 */
exports.DailyBudgetAlertSchema = (0, codegenv2_1.messageDesc)(exports.file_api_budget, 2);
/**
 * Describes the message blueapi.api.DailyRateIncreaseBudgetAlert.
 * Use `create(DailyRateIncreaseBudgetAlertSchema)` to create a new message.
 */
exports.DailyRateIncreaseBudgetAlertSchema = (0, codegenv2_1.messageDesc)(exports.file_api_budget, 3);
/**
 * Describes the message blueapi.api.MonthlyBudgetAlert.
 * Use `create(MonthlyBudgetAlertSchema)` to create a new message.
 */
exports.MonthlyBudgetAlertSchema = (0, codegenv2_1.messageDesc)(exports.file_api_budget, 4);
/**
 * Describes the message blueapi.api.CustomPeriodBudgetAlert.
 * Use `create(CustomPeriodBudgetAlertSchema)` to create a new message.
 */
exports.CustomPeriodBudgetAlertSchema = (0, codegenv2_1.messageDesc)(exports.file_api_budget, 5);
/**
 * Describes the message blueapi.api.BudgetAlertNotification.
 * Use `create(BudgetAlertNotificationSchema)` to create a new message.
 */
exports.BudgetAlertNotificationSchema = (0, codegenv2_1.messageDesc)(exports.file_api_budget, 6);
/**
 * Describes the message blueapi.api.BudgetAlertNotificationDetail.
 * Use `create(BudgetAlertNotificationDetailSchema)` to create a new message.
 */
exports.BudgetAlertNotificationDetailSchema = (0, codegenv2_1.messageDesc)(exports.file_api_budget, 7);
