// @generated by protoc-gen-es v2.7.0
// @generated from file api/budget.proto (package blueapi.api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { NotificationChannel } from "./notification_pb";

/**
 * Describes the file api/budget.proto.
 */
export declare const file_api_budget: GenFile;

/**
 * @generated from message blueapi.api.Budget
 */
export declare type Budget = Message<"blueapi.api.Budget"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Format: yyyy
   *
   * @generated from field: string fiscalYear = 2;
   */
  fiscalYear: string;

  /**
   * @generated from field: repeated blueapi.api.MonthlyBudget monthlyBudget = 3;
   */
  monthlyBudget: MonthlyBudget[];
};

/**
 * Describes the message blueapi.api.Budget.
 * Use `create(BudgetSchema)` to create a new message.
 */
export declare const BudgetSchema: GenMessage<Budget>;

/**
 * @generated from message blueapi.api.MonthlyBudget
 */
export declare type MonthlyBudget = Message<"blueapi.api.MonthlyBudget"> & {
  /**
   * Format: yyyymm
   *
   * @generated from field: string yearMonth = 1;
   */
  yearMonth: string;

  /**
   * @generated from field: double amount = 2;
   */
  amount: number;
};

/**
 * Describes the message blueapi.api.MonthlyBudget.
 * Use `create(MonthlyBudgetSchema)` to create a new message.
 */
export declare const MonthlyBudgetSchema: GenMessage<MonthlyBudget>;

/**
 * DailyBudgetAlert resource definition.
 *
 * @generated from message blueapi.api.DailyBudgetAlert
 */
export declare type DailyBudgetAlert = Message<"blueapi.api.DailyBudgetAlert"> & {
  /**
   * Required. threshold in budget alerts
   *
   * @generated from field: double value = 1;
   */
  value: number;

  /**
   * Required. notification enable/disable 
   * If disabled, no alert is sent.
   *
   * @generated from field: bool enabled = 2;
   */
  enabled: boolean;
};

/**
 * Describes the message blueapi.api.DailyBudgetAlert.
 * Use `create(DailyBudgetAlertSchema)` to create a new message.
 */
export declare const DailyBudgetAlertSchema: GenMessage<DailyBudgetAlert>;

/**
 * DailyRateIncreaseBudgetAlert resource definition.
 *
 * @generated from message blueapi.api.DailyRateIncreaseBudgetAlert
 */
export declare type DailyRateIncreaseBudgetAlert = Message<"blueapi.api.DailyRateIncreaseBudgetAlert"> & {
  /**
   * Required. threshold in budget alerts
   *
   * @generated from field: double value = 1;
   */
  value: number;

  /**
   * Required. notification enable/disable 
   * If disabled, no alert is sent.
   *
   * @generated from field: bool enabled = 2;
   */
  enabled: boolean;
};

/**
 * Describes the message blueapi.api.DailyRateIncreaseBudgetAlert.
 * Use `create(DailyRateIncreaseBudgetAlertSchema)` to create a new message.
 */
export declare const DailyRateIncreaseBudgetAlertSchema: GenMessage<DailyRateIncreaseBudgetAlert>;

/**
 * MonthlyBudgetAlert resource definition.
 *
 * @generated from message blueapi.api.MonthlyBudgetAlert
 */
export declare type MonthlyBudgetAlert = Message<"blueapi.api.MonthlyBudgetAlert"> & {
  /**
   * Required. threshold in budget alerts
   *
   * @generated from field: double value = 1;
   */
  value: number;

  /**
   * Required. notification enable/disable 
   * If disabled, no alert is sent.
   *
   * @generated from field: bool enabled = 2;
   */
  enabled: boolean;
};

/**
 * Describes the message blueapi.api.MonthlyBudgetAlert.
 * Use `create(MonthlyBudgetAlertSchema)` to create a new message.
 */
export declare const MonthlyBudgetAlertSchema: GenMessage<MonthlyBudgetAlert>;

/**
 * CustomPeriodBudgetAlert resource definition.
 *
 * @generated from message blueapi.api.CustomPeriodBudgetAlert
 */
export declare type CustomPeriodBudgetAlert = Message<"blueapi.api.CustomPeriodBudgetAlert"> & {
  /**
   * Required. threshold in budget alerts
   *
   * @generated from field: double value = 1;
   */
  value: number;

  /**
   * Required. notification enable/disable 
   * If disabled, no alert is sent.
   *
   * @generated from field: bool enabled = 2;
   */
  enabled: boolean;

  /**
   * Required. start date in budget alerts
   *
   * @generated from field: string startDate = 3;
   */
  startDate: string;

  /**
   * Required. end date in budget alerts
   *
   * @generated from field: string endDate = 4;
   */
  endDate: string;
};

/**
 * Describes the message blueapi.api.CustomPeriodBudgetAlert.
 * Use `create(CustomPeriodBudgetAlertSchema)` to create a new message.
 */
export declare const CustomPeriodBudgetAlertSchema: GenMessage<CustomPeriodBudgetAlert>;

/**
 * CustomMonthBudgetAlert resource definition.
 *
 * @generated from message blueapi.api.CustomMonthBudgetAlert
 */
export declare type CustomMonthBudgetAlert = Message<"blueapi.api.CustomMonthBudgetAlert"> & {
  /**
   * Required. threshold in budget alerts
   *
   * @generated from field: double value = 1;
   */
  value: number;

  /**
   * Required. notification enable/disable 
   * If disabled, no alert is sent.
   *
   * @generated from field: bool enabled = 2;
   */
  enabled: boolean;

  /**
   * Required. start day in budget alerts
   *
   * @generated from field: string startDay = 3;
   */
  startDay: string;
};

/**
 * Describes the message blueapi.api.CustomMonthBudgetAlert.
 * Use `create(CustomMonthBudgetAlertSchema)` to create a new message.
 */
export declare const CustomMonthBudgetAlertSchema: GenMessage<CustomMonthBudgetAlert>;

/**
 * BudgetAlertNotification resource definition.
 *
 * @generated from message blueapi.api.BudgetAlertNotification
 */
export declare type BudgetAlertNotification = Message<"blueapi.api.BudgetAlertNotification"> & {
  /**
   * Required. List of channelId. For example, you set to ["channelId1","channelId2","channelId3"].
   *
   * @generated from field: repeated string channels = 2;
   */
  channels: string[];

  /**
   * Required. notification enable/disable 
   * If disabled, no alert is sent.
   *
   * @generated from field: bool enabled = 3;
   */
  enabled: boolean;
};

/**
 * Describes the message blueapi.api.BudgetAlertNotification.
 * Use `create(BudgetAlertNotificationSchema)` to create a new message.
 */
export declare const BudgetAlertNotificationSchema: GenMessage<BudgetAlertNotification>;

/**
 * BudgetAlertNotificationDetail resource definition.
 *
 * @generated from message blueapi.api.BudgetAlertNotificationDetail
 */
export declare type BudgetAlertNotificationDetail = Message<"blueapi.api.BudgetAlertNotificationDetail"> & {
  /**
   * List of channel info.
   *
   * @generated from field: repeated blueapi.api.NotificationChannel channels = 2;
   */
  channels: NotificationChannel[];

  /**
   * Notification enable/disable 
   * If disabled, no alert is sent.
   *
   * @generated from field: bool enabled = 3;
   */
  enabled: boolean;
};

/**
 * Describes the message blueapi.api.BudgetAlertNotificationDetail.
 * Use `create(BudgetAlertNotificationDetailSchema)` to create a new message.
 */
export declare const BudgetAlertNotificationDetailSchema: GenMessage<BudgetAlertNotificationDetail>;

