// @generated by protoc-gen-es v2.5.0 with parameter "target=ts"
// @generated from file api/coverage.proto (package blueapi.api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/coverage.proto.
 */
export const file_api_coverage: GenFile = /*@__PURE__*/
  fileDesc("ChJhcGkvY292ZXJhZ2UucHJvdG8SC2JsdWVhcGkuYXBpIkoKC09wdGlvbnNEYXRhEgoKAmlkGAEgASgJEi8KDG9wdGlvbnNDaGFydBgCIAMoCzIZLmJsdWVhcGkuYXBpLk9wdGlvbnNDaGFydCJiCgxPcHRpb25zQ2hhcnQSDAoEZGF0ZRgBIAEoCRIMCgRjb3N0GAQgASgBEhAKCGNvdmVyYWdlGAIgASgBEg0KBXVzYWdlGAMgASgBEhUKDXVzYWdlQ292ZXJhZ2UYBSABKAEiTQoMT25kZW1hbmREYXRhEgoKAmlkGAEgASgJEjEKDW9uZGVtYW5kQ2hhcnQYAiADKAsyGi5ibHVlYXBpLmFwaS5PbmRlbWFuZENoYXJ0ImwKDU9uZGVtYW5kQ2hhcnQSDAoEZGF0ZRgBIAEoCRIPCgdzZXJ2aWNlGAIgASgJEhcKD25vcm1hbGl6ZWRVc2FnZRgDIAEoARIUCgxvbmRlbWFuZENvc3QYBCABKAESDQoFdXNhZ2UYBSABKAFCVQoZY2xvdWQuYWxwaGF1cy5ibHVlYXBpLmFwaUIQQXBpQ292ZXJhZ2VQcm90b1omZ2l0aHViLmNvbS9hbHBoYXVzbGFicy9ibHVlLXNkay1nby9hcGliBnByb3RvMw");

/**
 * @generated from message blueapi.api.OptionsData
 */
export type OptionsData = Message<"blueapi.api.OptionsData"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: repeated blueapi.api.OptionsChart optionsChart = 2;
   */
  optionsChart: OptionsChart[];
};

/**
 * Describes the message blueapi.api.OptionsData.
 * Use `create(OptionsDataSchema)` to create a new message.
 */
export const OptionsDataSchema: GenMessage<OptionsData> = /*@__PURE__*/
  messageDesc(file_api_coverage, 0);

/**
 * @generated from message blueapi.api.OptionsChart
 */
export type OptionsChart = Message<"blueapi.api.OptionsChart"> & {
  /**
   * @generated from field: string date = 1;
   */
  date: string;

  /**
   * @generated from field: double cost = 4;
   */
  cost: number;

  /**
   * @generated from field: double coverage = 2;
   */
  coverage: number;

  /**
   * @generated from field: double usage = 3;
   */
  usage: number;

  /**
   * @generated from field: double usageCoverage = 5;
   */
  usageCoverage: number;
};

/**
 * Describes the message blueapi.api.OptionsChart.
 * Use `create(OptionsChartSchema)` to create a new message.
 */
export const OptionsChartSchema: GenMessage<OptionsChart> = /*@__PURE__*/
  messageDesc(file_api_coverage, 1);

/**
 * @generated from message blueapi.api.OndemandData
 */
export type OndemandData = Message<"blueapi.api.OndemandData"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: repeated blueapi.api.OndemandChart ondemandChart = 2;
   */
  ondemandChart: OndemandChart[];
};

/**
 * Describes the message blueapi.api.OndemandData.
 * Use `create(OndemandDataSchema)` to create a new message.
 */
export const OndemandDataSchema: GenMessage<OndemandData> = /*@__PURE__*/
  messageDesc(file_api_coverage, 2);

/**
 * @generated from message blueapi.api.OndemandChart
 */
export type OndemandChart = Message<"blueapi.api.OndemandChart"> & {
  /**
   * @generated from field: string date = 1;
   */
  date: string;

  /**
   * @generated from field: string service = 2;
   */
  service: string;

  /**
   * @generated from field: double normalizedUsage = 3;
   */
  normalizedUsage: number;

  /**
   * @generated from field: double ondemandCost = 4;
   */
  ondemandCost: number;

  /**
   * @generated from field: double usage = 5;
   */
  usage: number;
};

/**
 * Describes the message blueapi.api.OndemandChart.
 * Use `create(OndemandChartSchema)` to create a new message.
 */
export const OndemandChartSchema: GenMessage<OndemandChart> = /*@__PURE__*/
  messageDesc(file_api_coverage, 3);

