// @generated by protoc-gen-es v2.7.0
// @generated from file api/forecast.proto (package blueapi.api, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file api/forecast.proto.
 */
export const file_api_forecast = /*@__PURE__*/
  fileDesc("ChJhcGkvZm9yZWNhc3QucHJvdG8SC2JsdWVhcGkuYXBpIsgBCgxGb3JlY2FzdERhdGESEQoJYWNjb3VudElkGAEgASgJEhcKD3Byb2R1Y3RDYXRlZ29yeRgCIAEoCRITCgtwcm9kdWN0Q29kZRgDIAEoCRIRCglmcmVxdWVuY3kYBCABKAkSDAoEZGF0ZRgFIAEoCRIWCg5oaXN0b3JpY2FsQ29zdBgGIAEoARIWCg5mb3JlY2FzdGVkQ29zdBgHIAEoARISCgp1cHBlckJvdW5kGAggASgBEhIKCmxvd2VyQm91bmQYCSABKAEiUAoUQWNjb3VudEdyb3VwRm9yZWNhc3QSDwoHZ3JvdXBJZBgBIAEoCRInCgRkYXRhGAIgAygLMhkuYmx1ZWFwaS5hcGkuRm9yZWNhc3REYXRhIloKFEJpbGxpbmdHcm91cEZvcmVjYXN0EhkKEWJpbGxpbmdJbnRlcm5hbElkGAEgASgJEicKBGRhdGEYAiADKAsyGS5ibHVlYXBpLmFwaS5Gb3JlY2FzdERhdGEiTQoLT3JnRm9yZWNhc3QSDQoFb3JnSWQYASABKAkSLwoEZGF0YRgCIAMoCzIhLmJsdWVhcGkuYXBpLkJpbGxpbmdHcm91cEZvcmVjYXN0IqcBChdNb250aFRvRGF0ZUZvcmVjYXN0RGF0YRIRCglhY2NvdW50SWQYASABKAkSFwoPcHJvZHVjdENhdGVnb3J5GAIgASgJEhMKC3Byb2R1Y3RDb2RlGAMgASgJEgwKBGRhdGUYBCABKAkSFwoPYWNjdW11bGF0ZWRDb3N0GAUgASgBEhQKDGZvcmVjYXN0Q29zdBgGIAEoARIOCgZidWRnZXQYByABKAEicAofQmlsbGluZ0dyb3VwTW9udGhUb0RhdGVGb3JlY2FzdBIZChFiaWxsaW5nSW50ZXJuYWxJZBgBIAEoCRIyCgRkYXRhGAIgAygLMiQuYmx1ZWFwaS5hcGkuTW9udGhUb0RhdGVGb3JlY2FzdERhdGEiYwoWT3JnTW9udGhUb0RhdGVGb3JlY2FzdBINCgVvcmdJZBgBIAEoCRI6CgRkYXRhGAIgAygLMiwuYmx1ZWFwaS5hcGkuQmlsbGluZ0dyb3VwTW9udGhUb0RhdGVGb3JlY2FzdCKFAQoTTW9udGhseUNvc3RGb3JlY2FzdBIMCgRkYXRlGAEgASgJEhIKCmNvc3RBY3R1YWwYAiABKAESFAoMY29zdEZvcmVjYXN0GAMgASgBEg4KBmJ1ZGdldBgEIAEoARISCgp1cHBlckJvdW5kGAUgASgBEhIKCmxvd2VyQm91bmQYBiABKAEiaQoYTW9udGhPbk1vbnRoQ29zdEZvcmVjYXN0EhAKCGNhdGVnb3J5GAEgASgJEhMKC2Nvc3RDdXJyZW50GAIgASgBEhAKCGNvc3RQcmV2GAMgASgBEhQKDGNvc3RGb3JlY2FzdBgEIAEoASKQAQoXTW9udGhUb0RhdGVDb3N0Rm9yZWNhc3QSDAoEZGF0ZRgBIAEoCRIQCghjb3N0UHJldhgCIAEoARIXCg9jb3N0QWNjdW11bGF0ZWQYAyABKAESFAoMY29zdEZvcmVjYXN0GAQgASgBEhIKCnVwcGVyQm91bmQYBSABKAESEgoKbG93ZXJCb3VuZBgGIAEoAUJVChljbG91ZC5hbHBoYXVzLmJsdWVhcGkuYXBpQhBBcGlGb3JlY2FzdFByb3RvWiZnaXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWUtc2RrLWdvL2FwaWIGcHJvdG8z");

/**
 * Describes the message blueapi.api.ForecastData.
 * Use `create(ForecastDataSchema)` to create a new message.
 */
export const ForecastDataSchema = /*@__PURE__*/
  messageDesc(file_api_forecast, 0);

/**
 * Describes the message blueapi.api.AccountGroupForecast.
 * Use `create(AccountGroupForecastSchema)` to create a new message.
 */
export const AccountGroupForecastSchema = /*@__PURE__*/
  messageDesc(file_api_forecast, 1);

/**
 * Describes the message blueapi.api.BillingGroupForecast.
 * Use `create(BillingGroupForecastSchema)` to create a new message.
 */
export const BillingGroupForecastSchema = /*@__PURE__*/
  messageDesc(file_api_forecast, 2);

/**
 * Describes the message blueapi.api.OrgForecast.
 * Use `create(OrgForecastSchema)` to create a new message.
 */
export const OrgForecastSchema = /*@__PURE__*/
  messageDesc(file_api_forecast, 3);

/**
 * Describes the message blueapi.api.MonthToDateForecastData.
 * Use `create(MonthToDateForecastDataSchema)` to create a new message.
 */
export const MonthToDateForecastDataSchema = /*@__PURE__*/
  messageDesc(file_api_forecast, 4);

/**
 * Describes the message blueapi.api.BillingGroupMonthToDateForecast.
 * Use `create(BillingGroupMonthToDateForecastSchema)` to create a new message.
 */
export const BillingGroupMonthToDateForecastSchema = /*@__PURE__*/
  messageDesc(file_api_forecast, 5);

/**
 * Describes the message blueapi.api.OrgMonthToDateForecast.
 * Use `create(OrgMonthToDateForecastSchema)` to create a new message.
 */
export const OrgMonthToDateForecastSchema = /*@__PURE__*/
  messageDesc(file_api_forecast, 6);

/**
 * Describes the message blueapi.api.MonthlyCostForecast.
 * Use `create(MonthlyCostForecastSchema)` to create a new message.
 */
export const MonthlyCostForecastSchema = /*@__PURE__*/
  messageDesc(file_api_forecast, 7);

/**
 * Describes the message blueapi.api.MonthOnMonthCostForecast.
 * Use `create(MonthOnMonthCostForecastSchema)` to create a new message.
 */
export const MonthOnMonthCostForecastSchema = /*@__PURE__*/
  messageDesc(file_api_forecast, 8);

/**
 * Describes the message blueapi.api.MonthToDateCostForecast.
 * Use `create(MonthToDateCostForecastSchema)` to create a new message.
 */
export const MonthToDateCostForecastSchema = /*@__PURE__*/
  messageDesc(file_api_forecast, 9);

