// @generated by protoc-gen-es v2.7.0
// @generated from file api/grouprootuser.proto (package blueapi.api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/grouprootuser.proto.
 */
export declare const file_api_grouprootuser: GenFile;

/**
 * Describes the fields on an Alphaus root user for a billing group or access group.
 *
 * @generated from message blueapi.api.GroupRootUser
 */
export declare type GroupRootUser = Message<"blueapi.api.GroupRootUser"> & {
  /**
   * The email address associated with the user. If there is no email
   * address provided then this field will contain "Not Set".
   *
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * The password associated with the user. This field will only be
   * populated when the reseller is first created.
   *
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * The ID of the group to which the user belongs. This will either
   * be a billing group ID or an access group ID.
   *
   * @generated from field: string groupId = 3;
   */
  groupId: string;

  /**
   * The name of the group to which the user belongs. This will either
   * be the name of a billing group or an access group.
   *
   * @generated from field: string groupName = 4;
   */
  groupName: string;

  /**
   * This field describes what type of group to which the user belongs.
   * This field will contain either a value of "billing_group" or "access_group".
   *
   * @generated from field: string groupType = 5;
   */
  groupType: string;

  /**
   * A collection of feature flags and whether or not they should be enabled. 
   * For a full list of such flags, see https://alphauslabs.github.io/blueapi/apis/groups.html.
   *
   * @generated from field: blueapi.api.FeatureFlags meta = 6;
   */
  meta?: FeatureFlags;

  /**
   * The time when the password was last updated. This value will be null if 
   * the password has never been updated.
   *
   * @generated from field: string passwordUpdateTime = 7;
   */
  passwordUpdateTime: string;

  /**
   * The time when the user was last updated. This value will be null if the
   * user has never been updated.
   *
   * @generated from field: string updateTime = 8;
   */
  updateTime: string;

  /**
   * An ID that uniquely identifies the user in the context of its access group.
   * If the user does not belong to an access group then this value field will
   * contain the same value as the user ID.
   *
   * @generated from field: string userAccessId = 9;
   */
  userAccessId: string;

  /**
   * An ID that unqiuely identifies the user.
   *
   * @generated from field: string userId = 10;
   */
  userId: string;

  /**
   * How many days of Wave use remain. This value is only used for trial accounts.
   * This field cannot be updated.
   *
   * @generated from field: int32 waveAvailabilityDays = 11;
   */
  waveAvailabilityDays: number;

  /**
   * When the user registered on Wave.
   *
   * @generated from field: string waveRegistered = 12;
   */
  waveRegistered: string;

  /**
   * The plan associated with the user. Possible values include "trial",
   * "limited3" and "limited4".
   *
   * @generated from field: string waveStatus = 13;
   */
  waveStatus: string;
};

/**
 * Describes the message blueapi.api.GroupRootUser.
 * Use `create(GroupRootUserSchema)` to create a new message.
 */
export declare const GroupRootUserSchema: GenMessage<GroupRootUser>;

/**
 * Describes the features and whether or not they are enabled for a particular user.
 *
 * @generated from message blueapi.api.FeatureFlags
 */
export declare type FeatureFlags = Message<"blueapi.api.FeatureFlags"> & {
  /**
   * Control view-access to the Wave dashboard graph
   *
   * @generated from field: bool dashboard_graph = 1;
   */
  dashboardGraph: boolean;

  /**
   * Control access to the Accounts pane under usage reports on Wave
   *
   * @generated from field: bool usage_account = 2;
   */
  usageAccount: boolean;

  /**
   * Control view-access to the Account-level graph under usage reports on Wave
   *
   * @generated from field: bool usage_account_graph = 3;
   */
  usageAccountGraph: boolean;

  /**
   * Control edit-access to Accounts under usage reports on Wave
   *
   * @generated from field: bool usage_account_menu_account_edit = 4;
   */
  usageAccountMenuAccountEdit: boolean;

  /**
   * Control view-access to budget settings for an Account under usage reports on Wave
   *
   * @generated from field: bool usage_account_menu_budget = 5;
   */
  usageAccountMenuBudget: boolean;

  /**
   * Control edit-access to budget settings for an Account under usage reports on Wave
   *
   * @generated from field: bool usage_account_menu_budget_edit = 6;
   */
  usageAccountMenuBudgetEdit: boolean;

  /**
   * Control view-access to the fees menu for an Account under usage reports on Wave
   *
   * @generated from field: bool usage_account_menu_fees_fee = 7;
   */
  usageAccountMenuFeesFee: boolean;

  /**
   * Control view-access to credits for an Account under usage reports on Wave
   *
   * @generated from field: bool usage_account_menu_fees_credit = 8;
   */
  usageAccountMenuFeesCredit: boolean;

  /**
   * Control view-access to refunds for an Account under usage reports on Wave
   *
   * @generated from field: bool usage_account_menu_fees_refund = 9;
   */
  usageAccountMenuFeesRefund: boolean;

  /**
   * Control view-access to other fees for an Account under usage reports on Wave
   *
   * @generated from field: bool usage_account_menu_fees_other_fees = 10;
   */
  usageAccountMenuFeesOtherFees: boolean;

  /**
   * Control download-access to usage report on Wave
   *
   * @generated from field: bool usage_report_download = 11;
   */
  usageReportDownload: boolean;

  /**
   * Control access to the Groups pane under usage reports on Wave
   *
   * @generated from field: bool usage_group = 12;
   */
  usageGroup: boolean;

  /**
   * Control view-access to the Group-level graph under usage reports on Wave
   *
   * @generated from field: bool usage_group_graph = 13;
   */
  usageGroupGraph: boolean;

  /**
   * Control view-access to the Tags pane under usage reports on Wave
   *
   * @generated from field: bool usage_tag = 14;
   */
  usageTag: boolean;

  /**
   * Control view-access to the Tag-level graph under usage reports on Wave
   *
   * @generated from field: bool usage_tag_graph = 15;
   */
  usageTagGraph: boolean;

  /**
   * Control view-access to the Tags pane for crosstag groups under usage reports on Wave
   *
   * @generated from field: bool usage_crosstag = 16;
   */
  usageCrosstag: boolean;

  /**
   * Control view-access to the Tag-level graph for crosstag groups under usage reports on Wave
   *
   * @generated from field: bool usage_crosstag_graph = 17;
   */
  usageCrosstagGraph: boolean;

  /**
   * Control view-access to purchased reservations under reserved instances on Wave
   *
   * @generated from field: bool ri_purchased = 18;
   */
  riPurchased: boolean;

  /**
   * Control access to RI utilization under reserved instances on Wave
   *
   * @generated from field: bool ri_utilization = 19;
   */
  riUtilization: boolean;

  /**
   * Control access to RI recommendations on Wave
   *
   * @generated from field: bool ri_recommendation = 20;
   */
  riRecommendation: boolean;

  /**
   * Control access to purchased savings plans on Wave
   *
   * @generated from field: bool sp_purchased = 21;
   */
  spPurchased: boolean;

  /**
   * Control access to the invoice on Wave
   *
   * @generated from field: bool invoice = 22;
   */
  invoice: boolean;

  /**
   * Control download-access to the discounted invoice CSV on Wave
   *
   * @generated from field: bool invoice_download_csv_discount = 23;
   */
  invoiceDownloadCsvDiscount: boolean;

  /**
   * Control download-access to the merged invoice CSV on Wave
   *
   * @generated from field: bool invoice_download_csv_merged = 24;
   */
  invoiceDownloadCsvMerged: boolean;

  /**
   * Control access to API tokens on Wave
   *
   * @generated from field: bool open_api = 25;
   */
  openApi: boolean;

  /**
   * Control access to sub-user management on Wave
   *
   * @generated from field: bool users_management = 26;
   */
  usersManagement: boolean;

  /**
   * Control access to the Coverage Ratio pane on Aqua
   *
   * @generated from field: bool aq_coverage_ratio = 27;
   */
  aqCoverageRatio: boolean;

  /**
   * Control access to the RI management pane on Aqua
   *
   * @generated from field: bool aq_ri_management = 28;
   */
  aqRiManagement: boolean;

  /**
   * Control access to the savings plan management pane on Aqua
   *
   * @generated from field: bool aq_sp_management = 29;
   */
  aqSpManagement: boolean;

  /**
   * Control access to RI and savings plan recommendations on Aqua
   *
   * @generated from field: bool aq_ri_sp_instances = 30;
   */
  aqRiSpInstances: boolean;

  /**
   * Control access to right-sizing on Aqua
   *
   * @generated from field: bool aq_right_sizing = 31;
   */
  aqRightSizing: boolean;

  /**
   * Control access to scheduling on Aqua
   *
   * @generated from field: bool aq_scheduling = 32;
   */
  aqScheduling: boolean;

  /**
   * Control access to the report filters pane in Wave Pro
   *
   * @generated from field: bool report_filters = 33;
   */
  reportFilters: boolean;

  /**
   * Control access to Aqua from Wave Pro
   *
   * @generated from field: bool aqua_link = 34;
   */
  aquaLink: boolean;

  /**
   * Control access to budget alerts from Wave Pro
   *
   * @generated from field: bool budgetalerts = 35;
   */
  budgetalerts: boolean;
};

/**
 * Describes the message blueapi.api.FeatureFlags.
 * Use `create(FeatureFlagsSchema)` to create a new message.
 */
export declare const FeatureFlagsSchema: GenMessage<FeatureFlags>;

