"use strict";
// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file api/keyvalue.proto (package blueapi.api, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeyValueMapSchema = exports.KeyValueSchema = exports.file_api_keyvalue = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
/**
 * Describes the file api/keyvalue.proto.
 */
exports.file_api_keyvalue = (0, codegenv2_1.fileDesc)("ChJhcGkva2V5dmFsdWUucHJvdG8SC2JsdWVhcGkuYXBpIiYKCEtleVZhbHVlEgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCSJPCgtLZXlWYWx1ZU1hcBILCgNrZXkYASABKAkSFQoLc3RyaW5nVmFsdWUYAiABKAlIABITCglib29sVmFsdWUYAyABKAhIAEIHCgV2YWx1ZUJVChljbG91ZC5hbHBoYXVzLmJsdWVhcGkuYXBpQhBBcGlLZXlWYWx1ZVByb3RvWiZnaXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWUtc2RrLWdvL2FwaWIGcHJvdG8z");
/**
 * Describes the message blueapi.api.KeyValue.
 * Use `create(KeyValueSchema)` to create a new message.
 */
exports.KeyValueSchema = (0, codegenv2_1.messageDesc)(exports.file_api_keyvalue, 0);
/**
 * Describes the message blueapi.api.KeyValueMap.
 * Use `create(KeyValueMapSchema)` to create a new message.
 */
exports.KeyValueMapSchema = (0, codegenv2_1.messageDesc)(exports.file_api_keyvalue, 1);
