// @generated by protoc-gen-es v2.5.0 with parameter "target=ts"
// @generated from file api/utilization.proto (package blueapi.api, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/utilization.proto.
 */
export const file_api_utilization: GenFile = /*@__PURE__*/
  fileDesc("ChVhcGkvdXRpbGl6YXRpb24ucHJvdG8SC2JsdWVhcGkuYXBpIkgKD1V0aWxpemF0aW9uRGF0YRIKCgJpZBgBIAEoCRIpCgljaGFydERhdGEYAiADKAsyFi5ibHVlYXBpLmFwaS5DaGFydERhdGEicQoJQ2hhcnREYXRhEgwKBGRhdGUYASABKAkSDwoHc2VydmljZRgCIAEoCRIMCgRjb3N0GAMgASgBEg4KBnByb2ZpdBgEIAEoARITCgt1dGlsaXphdGlvbhgFIAEoARISCgpjb21taXRtZW50GAYgASgBQlgKGWNsb3VkLmFscGhhdXMuYmx1ZWFwaS5hcGlCE0FwaVV0aWxpemF0aW9uUHJvdG9aJmdpdGh1Yi5jb20vYWxwaGF1c2xhYnMvYmx1ZS1zZGstZ28vYXBpYgZwcm90bzM");

/**
 * @generated from message blueapi.api.UtilizationData
 */
export type UtilizationData = Message<"blueapi.api.UtilizationData"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: repeated blueapi.api.ChartData chartData = 2;
   */
  chartData: ChartData[];
};

/**
 * Describes the message blueapi.api.UtilizationData.
 * Use `create(UtilizationDataSchema)` to create a new message.
 */
export const UtilizationDataSchema: GenMessage<UtilizationData> = /*@__PURE__*/
  messageDesc(file_api_utilization, 0);

/**
 * @generated from message blueapi.api.ChartData
 */
export type ChartData = Message<"blueapi.api.ChartData"> & {
  /**
   * @generated from field: string date = 1;
   */
  date: string;

  /**
   * @generated from field: string service = 2;
   */
  service: string;

  /**
   * @generated from field: double cost = 3;
   */
  cost: number;

  /**
   * @generated from field: double profit = 4;
   */
  profit: number;

  /**
   * @generated from field: double utilization = 5;
   */
  utilization: number;

  /**
   * @generated from field: double commitment = 6;
   */
  commitment: number;
};

/**
 * Describes the message blueapi.api.ChartData.
 * Use `create(ChartDataSchema)` to create a new message.
 */
export const ChartDataSchema: GenMessage<ChartData> = /*@__PURE__*/
  messageDesc(file_api_utilization, 1);

