name: Publish blue-sdk-ts package

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    if: '!contains(github.event.commits[0].message, "ci skip")'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@alphauslabs"

      - name: Install dependencies
        run: |
          npm install
          npm run build
          git config user.email "dev@mobingi.com"
          git config user.name "mobingideployer"
          git add . && git commit -am "$GITHUB_REF $GITHUB_SHA" || true
          git push
          npm version patch
          git add . && git commit -am "$GITHUB_REF $GITHUB_SHA" || true
          git push
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm publish
