name: package updater

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: write   # 🔥 REQUIRED to push

jobs:
  build:
    name: update package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # important for tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Publish & Push Version Update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          npm ci

          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Publishing version $VERSION"

          npm pkg set version=$VERSION
          npm publish --access public

          git add package.json
          git commit -m "chore: update package.json version to $VERSION" || echo "No changes"

          # push back to default branch (usually main)
          git push origin HEAD:main