// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file api/luster/comment.proto (package blueapi.api.luster, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/luster/comment.proto.
 */
export const file_api_luster_comment: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvbHVzdGVyL2NvbW1lbnQucHJvdG8SEmJsdWVhcGkuYXBpLmx1c3RlciJqCgdDb21tZW50EgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSDwoHY29udGVudBgDIAEoCRIOCgZ1c2VySWQYBCABKAkSEQoJY3JlYXRlZEF0GAUgASgJEhEKCXVwZGF0ZWRBdBgGIAEoCUJoCiBjbG91ZC5hbHBoYXVzLmJsdWVhcGkuYXBpLmx1c3RlckIVQXBpTHVzdGVyQ29tbWVudFByb3RvWi1naXRodWIuY29tL2FscGhhdXNsYWJzL2JsdWUtc2RrLWdvL2FwaS9sdXN0ZXJiBnByb3RvMw");

/**
 * The message defines the comment
 *
 * @generated from message blueapi.api.luster.Comment
 */
export type Comment = Message<"blueapi.api.luster.Comment"> & {
  /**
   * The comment id.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The comment name.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * The comment content.
   *
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * The comment userId.
   *
   * @generated from field: string userId = 4;
   */
  userId: string;

  /**
   * The comment createdAt.
   * "created_at": "2023-10-27T10:00:00Z"
   *
   * @generated from field: string createdAt = 5;
   */
  createdAt: string;

  /**
   * The comment updatedAt.
   * "updated_at": "2023-10-27T10:00:00Z"
   *
   * @generated from field: string updatedAt = 6;
   */
  updatedAt: string;
};

/**
 * Describes the message blueapi.api.luster.Comment.
 * Use `create(CommentSchema)` to create a new message.
 */
export const CommentSchema: GenMessage<Comment> = /*@__PURE__*/
  messageDesc(file_api_luster_comment, 0);

