// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file api/luster/space.proto (package blueapi.api.luster, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/luster/space.proto.
 */
export const file_api_luster_space: GenFile = /*@__PURE__*/
  fileDesc("ChZhcGkvbHVzdGVyL3NwYWNlLnByb3RvEhJibHVlYXBpLmFwaS5sdXN0ZXIiewoFU3BhY2USCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIPCgdtZW1iZXJzGAQgAygJEhgKCmNyZWF0ZWRfYXQYBSABKAlCBOJBAQMSGAoKdXBkYXRlZF9hdBgGIAEoCUIE4kEBA0JmCiBjbG91ZC5hbHBoYXVzLmJsdWVhcGkuYXBpLmx1c3RlckITQXBpTHVzdGVyU3BhY2VQcm90b1otZ2l0aHViLmNvbS9hbHBoYXVzbGFicy9ibHVlLXNkay1nby9hcGkvbHVzdGVyYgZwcm90bzM", [file_google_api_field_behavior]);

/**
 * The message defines the space
 *
 * @generated from message blueapi.api.luster.Space
 */
export type Space = Message<"blueapi.api.luster.Space"> & {
  /**
   * The space id.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The space name.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * The space description.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * The members in space.
   *
   * @generated from field: repeated string members = 4;
   */
  members: string[];

  /**
   * The space created_at.
   * "created_at": "2023-10-27T10:00:00Z"
   *
   * @generated from field: string created_at = 5;
   */
  createdAt: string;

  /**
   * The space updated_at.
   * "updated_at": "2023-10-27T10:00:00Z"
   *
   * @generated from field: string updated_at = 6;
   */
  updatedAt: string;
};

/**
 * Describes the message blueapi.api.luster.Space.
 * Use `create(SpaceSchema)` to create a new message.
 */
export const SpaceSchema: GenMessage<Space> = /*@__PURE__*/
  messageDesc(file_api_luster_space, 0);

